### ISSUE TITLE
Assets coming from home assistant IP when behind reverse proxy

### ISSUE THREAD

**Issue by iamandymcinnes** [hassio-addons/addon-grocy#10]
# Problem/Motivation
I have home assistant running on a PI within my network on an IP e.g. 192.168.1.51, I use IIS to reverse proxy home assistant and any other service. E.g. home assistant home.mydomain.com and grocy.mydomain.com. Meaning I don't need to expose ports to the outside world to access resources. The SSL is also on my web server for each sub domain.

I see the grocy loading under the proxied sub domain under the HTTPS as expected, but for some reason assets are being loaded by IP on HTTP and so are blocked.

login:1 Mixed Content: The page at 'https://grocy.mydomain.co.uk/login' was loaded over HTTPS, but requested an insecure favicon 'http://192.168.1.51:9192/img/appicons/favicon.ico?v=2.2.0'. This request has been blocked; the content must be served over HTTPS.

This goes for all js, css, font, etc

## Expected behavior

Load the assets under the same domain as the site under HTTPS

## Actual behavior

Loaded as HTTP 

## Steps to reproduce

Install addon in home assistant
Leave SSL off in settings as this is setup on IIS
Create a reverse proxy rule directing 80/443 for the domain to the IP and port of Grocy running on home assistant.
Create a rule to Rewrite HTTP > HTTPS

## Proposed changes

I'm not entirely sure what needs changing but perhaps use the the request details to load other assets with the request url as the base url. I am successfully using the above setup on numerous other addons, including configurator without issue.

**Comment by sinclairpaul** [comment]
Could you share the IIS log line for the request?, are the messages posted in the browser?, if so I'm not sure URL Rewrite is working as you shouldn't see the backend request.

**Comment by sinclairpaul** [comment]
Closing this off as will assume its resolved.  Please feel free to reopen an issue if needed.
