### ISSUE TITLE
Invalid credentials after first set-up

### ISSUE THREAD

**Issue by sondreen** [hassio-addons/addon-grocy#101]
# Problem/Motivation

After logging out all credentials are returned as invalid.

## Expected behavior

Logging in with credentials created in UI.

## Actual behavior

After setting up Grocy on two occasions on OS HassOS 5.6 Core 0.118.4 Supervisor 2020.11.0 it denies access with invalid credentials on all users after logging out, this includes admin, even though credentials are copy-pasted directly. Have tried re-installing the add-on, restarting the add-on and the server. Tried with all users and credentials.

## Steps to reproduce

1. Install add-on.
2. Configure per readme.
3. Login with preset admin-credentials.
4. Go to user-settings in UI.
5. Create new users with credentials.
6.. Log out.
7. Log back in with any new credentials.

**Comment by sondreen** [comment]
After a third reinstall, restart and new configure it seems to be working fine for the moment, I'll keep an eye on it over the night and close this if all OK.

**Comment by frenck** [comment]
Since you did not come back at this, and I'm not able to reproduce it: Closing the issue.
