### ISSUE TITLE
Instructions/Dependencies for building and running manually

### ISSUE THREAD

**Issue by krmoffett** [hassio-addons/addon-grocy#102]
# Problem/Motivation

> Some installations of Home Assistant don't support Supervisor so add-ons need to be configured manually. There currently aren't any instructions for installation without Supervisor.

**Comment by sinclairpaul** [comment]
Addons are designed to utilise the Supervisor.  If you want to run the software yourself, please see the relevant source (for example the Grocy Github repo).
