### ISSUE TITLE
Upgrade to latest version (3.0.0)

### ISSUE THREAD

**Issue by Daniel-Tyler-Farmer** [hassio-addons/addon-grocy#104]
First: Thanks for an awesome addon. Just curious, is there a plan to upgrade to the latest release any time soon?

### **Problem/Motivation**
Eager to get the latest version of grocy via home assistant addon

**Expected behavior**
An install of version 3.0.0 via this addon

**Actual behavior**
2.7.1 installs

**Steps to reproduce**
Install Grocy as an addon via home assistant supervisor

**Proposed changes**
Update this addon to build from release 3.0.0

**Comment by frenck** [comment]
That is not an issue, but an request.

There are many updates pending, most importantly infra structure updates. The latter has a priority right now.

**Comment by Nossnevs** [comment]
> That is not an issue, but an request.
> 
> There are many updates pending, most importantly infra structure updates. The latter has a priority right now.

Can you share what they are? (See if i can help make 3.0.0 happen faster.)

**Comment by koenieee** [comment]
Yeah I'm wondering the same, is it possible to update manually?

**Comment by frenck** [comment]
You can't update manually. The whole project is currently in a migration process to make everything possible again and allow for faster future shipping in general.
