### ISSUE TITLE
No such column: barcode 

### ISSUE THREAD

**Issue by schmacka** [hassio-addons/addon-grocy#126]
# Problem/Motivation
When adding items to the stock via barcode-buddy ((Homeassistant supervisor addon) the following error occurs. It seems the barcode column in Grocy is missing.

Adding barcodes directly via grocy web interface works though.

Grocy 3.0.1 via Homeassistant supervisor addon. Even did a clean install of both grocy and barcode-buddy homeassistant addon

## Actual behavior

> 2021-01-30 06:55:54: Adding 1 Packung of Frosch Limonen Spülmittel [WARNING]: No default best before date set!
> 2021-01-30 06:55:54: Associated barcode 4001499944604 with Frosch Limonen Spülmittel
> 2021-01-30 06:55:54: Invalid JSON: Could not set Grocy barcode SQLSTATE[HY000]: General error: 1 no such column: barcode Please check your URL and API key in the settings menu!

## Steps to reproduce
Scan item and add it via barcode-buddy

Looking through the webs I found the exact same issue. 
#https://github.com/grocy/grocy/issues/1176

So I basically have two questions:

1. Is there an issue with the base image which can be fixed through an update
or
2. should I try to fix it like in the linked issue.

**Comment by JSteeleIR** [comment]
This is still an issue in the latest version available.
