### ISSUE TITLE
Not working with SSL

### ISSUE THREAD

**Issue by aluisperezh** [hassio-addons/addon-grocy#13]
# Problem/Motivation

Grocy installed as an add-on in Home Assistant working in a Raspberry Pi 3 B+ with Raspbian. Enabling SSL and accessing the start page (https://mydomain.duckdns.org:9192) always delivers a 404 with no other info.

The only line in /var/log/nginx/error.log is this:

`2019/04/08 09:26:12 [error] 711#711: *1 open() "/var/www/grocy/public/recipes" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx (redacted), server: hassio.local, request: "GET /recipes HTTP/1.1", host: "mydomain.duckdns.org:9192 (redacted)"`

Disabling SSL makes the add-on work as expected, but cannot be integrated in HA main screen.

I checked /ssl directory and the certificates are there.

Other add-ons (Configurator, Node-Red, Traccar) work fine with SSL.

## Expected behavior

It should work with HTTPS as it works without SSL

## Actual behavior

404 Not found. 

No other info found on screen or in log files

## Steps to reproduce

Just enable SSL in the config file.

## Proposed changes

Nothing I can think off. I don't know if there is something else I should do before enabling SSL

**Comment by frenck** [comment]
Fixed in the current development branch. Thanks for reporting.
