### ISSUE TITLE
After fresh install on Home Assistant the fonts are different from the original

### ISSUE THREAD

**Issue by 1endell** [hassio-addons/addon-grocy#136]
I just installed the Add-on in the supervisor tab, as done in every add-on. After started, the font in all the add-on is like a seven-segment led display. It's nice, but not much readable. 

Thanks guys!

**Comment by frenck** [comment]
I'm not sure what you mean? Could you maybe clarify it with a screenshot?

**Comment by 1endell** [comment]
This is the screen i see after a fresh install:

![Grocy](https://user-images.githubusercontent.com/4711579/107789917-f323ce80-6d30-11eb-97ba-9faae57279c9.JPG)

**Comment by frenck** [comment]
Uh wut?!

![](https://media4.giphy.com/media/FxEwsOF1D79za/giphy.gif)

**Comment by 1endell** [comment]
Its true, bro. I don't know how it happened too. I've also installed using portainer in a Docker container, from the linuxserver/grocy:latest image, but happened the same. Using Chrome, with the Inspector, it only turned normal when i unchecked the box, in the image:
![image](https://user-images.githubusercontent.com/4711579/107801094-68e26700-6d3e-11eb-8fd2-663fc25b166e.png)

**Comment by frenck** [comment]
🤷 This is fully outside of the scope the add-on can even cause such a thing. Have you checked with a different browser?

**Comment by 1endell** [comment]
You're right. The last screenshot i took was  when i was trying to understand what was happening. It didn't happened now, with the Firefox. I'm gonna close the issue. Sorry to bother. I'm a big fan of your work.
