### ISSUE TITLE
Failed to start addon after update to 0.12.0

### ISSUE THREAD

**Issue by ChiaraSand** [hassio-addons/addon-grocy#158]
Hey there!
First of all: THANK YOU very much for this addon. I am so happy about it!
Unfortunately it doesn't work anymore after updating.
This is the first issue I ever wrote so if I missed something please tell me. :)

# UPDATE
It's working again. See Edit2 below.

# Problem/Motivation

Couldn't start addon after updating to 0.12.0
At first I had "502: Bad Gateway" after updating. I got 502 sometimes before but normally a page reload or addon restart helped. This time it didn't help. 
After restarting the addon I could't access or start grocy anymore. "Add-on is not running. Please start it first"

## Expected behavior

Start normally.

## Actual behavior

Does not start.

## Steps to reproduce

Update to 0.12.0, try to use web UI.

## Proposed changes

I think this is a problem that occurs only after updating. A fresh install shouldn't have this problem. 
Is there an option to add this config-line to already installed ones via an update?

## Addon Error

`Missing option 'stock_count_opened_products_against_minimum_stock_amount' in tweaks in Grocy (a0d7b954_grocy).`

## Supervisor log

```
21-04-05 16:02:36 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_grocy!
21-04-05 16:02:38 ERROR (MainThread) [supervisor.addons.addon] Add-on a0d7b954_grocy has invalid options: Missing option 'stock_count_opened_products_against_minimum_stock_amount' in tweaks in Grocy (a0d7b954_grocy). Got {'culture': 'de', 'currency': 'EUR', 'entry_page': 'stock', 'features': {'batteries': True, 'calendar': True, 'chores': True, 'equipment': True, 'recipes': True, 'shoppinglist': True, 'stock': True, 'tasks': True}, 'tweaks': {'chores_assignment': True, 'multiple_shopping_lists': True, 'stock_best_before_date_tracking': True, 'stock_location_tracking': True, 'stock_price_tracking': True, 'stock_product_freezing': True, 'stock_product_opened_tracking': True}, 'ssl': False, 'certfile': 'fullchai...
21-04-05 16:02:38 ERROR (MainThread) [supervisor.misc.tasks] a0d7b954_grocy watchdog reanimation failed with 
21-04-05 16:03:05 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 0.0.0.0:8099 ssl:default [Connect call failed ('0.0.0.0', 8099)]
```

## Home Assistant Info

```
Core
Version: core-2021.3.4
Newest Version: core-2021.3.4
```
```
Supervisor
Version: supervisor-2021.03.9
Newest Version: supervisor-2021.03.9
Channel: stable
```
```
Host
Operating System: Home Assistant OS 5.12
Deployment: production
```

## Screenshots
Error after clicking "Start":
<img width="509" alt="Screenshot 2021-04-05 at 18 04 41" src="https://user-images.githubusercontent.com/40384044/113595880-e0938a80-9639-11eb-8acc-e54437963ce7.png">

Supervisor log:
<img width="1443" alt="Screenshot 2021-04-05 at 18 04 54" src="https://user-images.githubusercontent.com/40384044/113595932-ef7a3d00-9639-11eb-916f-647eeee19413.png">

Greetings from Germany!

## EDIT:

Added Supervisor log as code

## EDIT2:

Added Missing option 'stock_count_opened_products_against_minimum_stock_amount' to my config and rebooted my raspberry pi. It's working again!

**Comment by frenck** [comment]
Thanks, Updated the release notes to mention this 👍
