### ISSUE TITLE
Support for Ingress

### ISSUE THREAD

**Issue by jeffglousher** [hassio-addons/addon-grocy#16]
# Problem/Motivation

Feature Request - I am placing this issue as a request for support of the new ingress feature. 

## Expected behavior

Support ingress with the add on

## Actual behavior

Add on does not support ingress

## Steps to reproduce

Install current version.

## Proposed changes

Support ingress to increase ease of use and barrier of entry for less skilled users.

**Comment by frenck** [comment]
This add-on is not able to support ingress.

**Comment by Bradley-Cooley** [comment]
@frenck Hi there, could you give the specific reason why grocy cannot support Ingress? I was thinking of trying to tackle this personally to dip my toes into HA add-on development, and I would like to know why it's not feasible. Thanks.

**Comment by frenck** [comment]
@Bradley-Cooley Because both Hass.io's Ingress and Grocy don't handle reverse proxying in subfolders correctly (which essentially is what Ingress does).

Even with a bunch of sub_filters, it simply won't work reliably. So unless both parties make adjustments, this add-on won't be viable for the Hass.io Ingress feature.

**Comment by fbartels** [comment]
https://github.com/grocy/grocy/issues/54 makes it seem like Grocy itself is able to run in a subfolder but

1. would then need to know the path its running ins (e.g. hassio:8123/path_grocy)
2. would always need to be executed from this path (you cannot mix direct port access and running in path)

2 would be easy to adjust by just adding a redirect from / to the desired path (with the downside that if people bookmarked sublocations these would error out)
for 1 I guess hassio would need to allow to specify the id for ingress?
