### ISSUE TITLE
Update broke grocy

### ISSUE THREAD

**Issue by samnewman86** [hassio-addons/addon-grocy#160]
# Problem/Motivation
Grocy doesn't start after update.
Errors in supervisor log.
Fixed by adding the following option in the tweaks section of add-on config.
`stock_count_opened_products_against_minimum_stock_amount: true`
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
See release notes: <https://github.com/hassio-addons/addon-grocy/releases/tag/v0.12.0>
