### ISSUE TITLE
Consuming Items Doesnt Always Work

### ISSUE THREAD

**Issue by marc25v** [hassio-addons/addon-grocy#17]
# Problem/Motivation

> When consuming items, the fields go gray, but nothing happens.  To actually change inventory, I need to use the Inventory button or the buttons on the stock overview screen.

## Expected behavior

> When selecting an item and specifying the quantity to consume, it should do so.

## Actual behavior

> Entering details to consume and pressing OK or Opened, just makes the fields go gray, but nothing happens.

## Steps to reproduce

> See above.
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please report this @ Grocy itself. From the add-on perspective, there is not much I can do about this.
