### ISSUE TITLE
Grocy is only available for admins

### ISSUE THREAD

**Issue by RubenKelevra** [hassio-addons/addon-grocy#173]
As already discussed in #94 Grocy is only available for admins, due to a Home Assistant restriction.

Is there a way to open a local port to be able to connect via the LAN or via VPN to it?

I don't see a point having all users being admins just to be able to use grocy :/

**Comment by sinclairpaul** [comment]
An external port can be specified on the Addon Configuration page under the Network section.

![image](https://user-images.githubusercontent.com/24625998/117852373-3ff64300-b255-11eb-99fc-67130cb1b7f3.png)
