### ISSUE TITLE
Error when changing grocy tabs

### ISSUE THREAD

**Issue by NicciZar** [hassio-addons/addon-grocy#178]
# Problem/Motivation

> I get an error message when switching grocy tabs

## Expected behavior

> No message (dont know what works/ what doesnt)

## Actual behavior

> An error message appears with ""{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key\"}""

## Steps to reproduce

> Log into grocy, switch tabs inside grocy web application

**Comment by frenck** [comment]
```
An error message appears with ""{"error_message":"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key"}""
```

That is not an add-on issue, but a issue with the application that the add-ons wraps (Grocy in this case). Please report your issue upstream. If it gets fixed, it will land in the add-on as an update as well.
