### ISSUE TITLE
How do I add the Grocy BuddyScanner application

### ISSUE THREAD

**Issue by NicciZar** [hassio-addons/addon-grocy#179]
# Problem/Motivation

> I cannot add the buddyscanner app from my android phone to this Grocy instance..
> I would like to use it so I can scan my stuff

## Expected behavior

> inside the original (updated?) grocy there is a barcode scanner tab and I have to enable that option first before using it.. which
> which is not the case 

## Actual behavior

> No option to add it

## Steps to reproduce

> Not necessary here I believe

## Proposed changes

> I would like to know IF its possible and if not if you could add this feature to this version (or update?)

**Comment by frenck** [comment]
See barcode buddy documentation: <https://barcodebuddy-documentation.readthedocs.io/en/latest/setup.html#hass-io>
