### ISSUE TITLE
Feature request: Support embedded flag

### ISSUE THREAD

**Issue by mkerner** [hassio-addons/addon-grocy#18]
# Problem/Motivation
When using the embedded flag authentication is not required. This works better under the umbrella authentication of Home Assistant (it's possible this might also facilitate Ingress better)

## Expected behavior
It would be ideal to not have to login again.

**Comment by pixeldublu** [comment]
+1 for Ingress

**Comment by frenck** [comment]
Ingress is not going to happen @pixeldublu.

**Comment by pixeldublu** [comment]
could you detail why ?

**Comment by timmo001** [comment]
@pixeldublu take a look at this comment:

https://github.com/hassio-addons/addon-grocy/issues/16#issuecomment-488847060

**Comment by pixeldublu** [comment]
Thanks !
