### ISSUE TITLE
Purchase UI freezes, can't add anything to inventory

### ISSUE THREAD

**Issue by codingcatgirl** [hassio-addons/addon-grocy#187]
So… hasa there been any discussion about [this issue](https://github.com/grocy/grocy/issues/882) on here? It only seems to affect the home assistant add on, and i'm experiencing this issue as well.

# Problem/Motivation

Purchase screen freezes when clicking okay, nothing happens, not even a HTTP request is fired it seems like. 

## Expected behavior

I can add items to inventory.

## Actual behavior

Purchase screen freezes when clicking okay, nothing happens, not even a HTTP request is fired it seems like. 

## Steps to reproduce

Try to add an item via purchase, that's it. You can't.

I'm running hassio on a raspberry pi.

**Comment by codingcatgirl** [comment]
I can ssay this: it does seem to be caused by deactivating `stock_location_tracking`. After reinstalling grocy (just changing the configuration and restarting it didn't seem to do anything?) and not disabling the feature, i can add products alright. So… there's a bug related to that option.

**Comment by frenck** [comment]
Bug related to the option should be reported upstream. We don't develop Grocy itself.

Thanks 👍

**Comment by codingcatgirl** [comment]
As you can read in the issue i linked above, this issue seems to be unpeproducible upstream and only happens with your add-on.

**Comment by sinclairpaul** [comment]
I can duplicate this, I actually think that the environment variables may need to be set to "true", "false" rather than 0 or 1, needs some further investigation

**Comment by sinclairpaul** [comment]
So yeah if I do:
```
if bashio::config.false 'tweaks.stock_location_tracking'; then
    export GROCY_FEATURE_FLAG_STOCK_LOCATION_TRACKING=false
fi
```
As opposed to:
```
if bashio::config.false 'tweaks.stock_location_tracking'; then
    export GROCY_FEATURE_FLAG_STOCK_LOCATION_TRACKING=0
fi
```
The error doesn't occur and the location field is inactive.



The error doesn't occur and the
