### ISSUE TITLE
Grocy can't be restored from snapshot

### ISSUE THREAD

**Issue by codingcatgirl** [hassio-addons/addon-grocy#188]
# Problem/Motivation

I tried to restore grocy from a snapshot, now it fails with the following error message (in ingress):

> Unable to run grocy: config.php in data directory (/var/www/grocy/public/../data) not found. Have you copied config-dist.php to the data directory and renamed it to config.php?

## Expected behavior

I should be able to restore grocy from a snapshot.

## Actual behavior

Restoring grocy from a snapshot breaks grocy.

## Steps to reproduce

- Install Grocy
- Make a snapshot
- (possibly edit something that is contained in the snapshot, not sure if necessary?)
- Restore the snapshot 
- Try to open the grocy panel

**Comment by frenck** [comment]
I've just followed the steps, but I'm unable to reproduce this :(

**Comment by frenck** [comment]
Closing, no reponse.
