### ISSUE TITLE
Grocy Won't Start

### ISSUE THREAD

**Issue by qJake** [hassio-addons/addon-grocy#19]
## Problem

Nginx won't start (therefore, Grocy does not start).

## Log File

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-grocy: applying... 
[fix-attrs.d] 01-grocy: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: HassOS 2.11  (armv7 / raspberrypi3)
 Home Assistant version: 0.92.2
 Supervisor version: 162
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[cont-init.d] grocy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:57:22] INFO: Starting PHP-FPM...
[22:57:25] INFO: Starting NGinx....
```

Presumably, there should be something after "Starting NGinx...", right? That's the last entry, there is nothing after that. I let it sit for quite some time (over 10min).

## Config

```json
{
  "culture": "en",
  "currency": "$",
  "features": {
    "batteries": false,
    "calendar": false,
    "chores": false,
    "equipment": true,
    "recipes": true,
    "shoppinglist": true,
    "tasks": false
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
```

## Status

Supervisor reports addon is "running":

![image](https://user-images.githubusercontent.com/652006/57426923-2a259180-71e7-11e9-9897-4867ff5e3c95.png)

## Browsing

When loading the page at https://&lt;my-hassio-domain&gt;:9192/, I get the following error:

![image](https://user-images.githubusercontent.com/652006/57427017-a6b87000-71e7-11e9-9ed8-1aa684602979.png)

**Comment by Krinogen** [comment]
Same problem here
-----------------------------------------------------------
 Hass.io Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: HassOS 2.12  (aarch64 / odroid-c2)
 Home Assistant version: 0.93.1
 Supervisor version: 164

**Comment by qJake** [comment]
Ah, I got this to work. It's not clear in the documentation (which I can update / PR), but **for Hass.io installations**, your target URL is going to be `http://<Your-LAN-IP>:9192/`. You should also set `ssl: false` in your configuration because your Hass.io public certificate probably won't work on your internal IP address.

@Krinogen if this wasn't your issue then I suggest opening a new issue separately, since I'm marking this as closed.
