### ISSUE TITLE
Unable to consume more than 1 at a time

### ISSUE THREAD

**Issue by SupremeSports** [hassio-addons/addon-grocy#190]
# Problem/Motivation

> Unable to consume more than 1 at a time

## Expected behavior

> In the consume tab, we should be able to consume multiple of the same item (example, used 3 eggs so I consume 3)

## Actual behavior

> Getting the message "This must between 0.0001 and 1 and needs to be a valid number with max. 4 decimal places"

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not an add-on bug, but one with Grocy itself.

Please report this issue with the Grocy project. Once it has been fixed upstream, the add-on will update to include that fix.

../Frenck
