### ISSUE TITLE
All items have no location

### ISSUE THREAD

**Issue by SupremeSports** [hassio-addons/addon-grocy#191]
# Problem/Motivation

> All pre-existing items has no location and I'm unable to set one or to transfer them to a location

## Expected behavior

> I should be at least able to set one while transferring or changing the inventory

## Actual behavior

> Error message saying "A location is required" and unable to do anything with the item, there's no choices in the drop-down menus

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there @SupremeSports 👋 

That is no an add-on issue, but a bug with Grocy. Add-ons wrap existing software, in this case, Grocy. Please report your issue with Grocy, if it is fixed, the add-on will update to include that fix.

../Frenck
