### ISSUE TITLE
Manage Master Data functionality broken when accessing using external domain/subdomain

### ISSUE THREAD

**Issue by diagonali** [hassio-addons/addon-grocy#212]
I'm using DuckDNS and the Nginx Proxy Manager Addon to access the Grocy addon from the following URL format:

https://gr.mydomain.duckdns.org/

Attempting to use any functionality using "Manage master data" such as adding Products, Locations, Stores etc results in this an error

Eg click Stores > Click "Add", fill out Store name, click save:

```
Error while saving, probably this item already exists
Click to show technical details
```

```
Error details
""
```

This is happening throughout the Grocy interface in other places.

This error _doesn't happen_ when accessing Grocy from within the Home Assistant interface.

I know some changes were recently made to fix some URL handling issues when handling access externally. I think maybe a few tweaks to this to handle the URL structure I've used (and which could be used by others) could help fix the issue and would be much appreciated as I'm hoping to use [this app](https://github.com/patzly/grocy-android) to access Grocy functionality once it's out of Beta. Thanks

**Comment by HydrelioxGitHub** [comment]
Same issue here.

**Comment by andreheuer** [comment]
Sounds for me like the same issue as in #208. If it is working when using Grocy via lovelace interface, it is definitely the same issue. PR #209 has been raised, waiting for integration.

**Comment by HydrelioxGitHub** [comment]
I still have this issue.

**Comment by georgegebbett** [comment]
Issue is still ongoing
