### ISSUE TITLE
Data does not show when accessing grocy directly on the host

### ISSUE THREAD

**Issue by tiborverlics** [hassio-addons/addon-grocy#213]
# Problem:
I have grocy installed as addon, and was trying to set up a link on my phone so I can access grocy directly instead of going through the homeassistant app. However when I open grocy directly, the whole UI seems to be empty without any data

## Expected behavior

I'd expect all data that I have in grocy to show up the same way with data populate when going directly to grocy as https://host:9192 as I have when I access through the homeassistant app:
![image](https://user-images.githubusercontent.com/18633008/128746773-3ebeb487-46b1-40d8-a88b-b498180b3bf2.png)

## Actual behavior

Grocy shows up empty when I try to access directly as https://host:9192
![image](https://user-images.githubusercontent.com/18633008/128745299-09cdfd30-0668-4ff6-b0dd-dd6ac86a319f.png)

## Steps to reproduce

opening grocy directly as https://host:9192 instead of through homeassistant

**Comment by xBourner** [comment]
having the same

**Comment by DaveVanVerdegem** [comment]
A fix is waiting to be merged through pull request #209.
