### ISSUE TITLE
Getting Page not Found after disabling Equipment

### ISSUE THREAD

**Issue by Jeltel** [hassio-addons/addon-grocy#24]
Grocy displays a Page Not Found 404 when disabling Equipment in the Config.

Working:
```
{
  "culture": "nl",
  "currency": "€",
  "features": {
    "batteries": false,
    "calendar": true,
    "chores": false,
    "equipment": true,
    "recipes": true,
    "shoppinglist": true,
    "stock": true,
    "tasks": false
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
```
Not working:
```{
  "culture": "nl",
  "currency": "€",
  "features": {
    "batteries": false,
    "calendar": true,
    "chores": false,
    "equipment": false,
    "recipes": true,
    "shoppinglist": true,
    "stock": true,
    "tasks": false
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
```

When going to my grocy page localhost:9192 it is diverted to: localhost:9192/equipment. But I have that disabled, so it's not finding that page.
I want it to go to localhost:9192/stockoverview

**Comment by frenck** [comment]
That is probably because you visited that page the last time.
By default, Grocy will redirect to stockoverview.

Clear you browser cache or try incognito.

**Comment by Jeltel** [comment]
Nope. 
I've never enabled equipment (ok, maybe only on the first run ages ago.) We always use the stockoverview. But with version 0.2.0 (and 0.3.0 still) it always reverts to equipment.

**Comment by frenck** [comment]
I have no reproduction for this... 
Cannot get mine in a state where it does this, which is an issue since I won't allow me to debug or fix this.

**Comment by Jeltel** [comment]
I can share a snapshot from this. I'll change the passwords first. Don't care if you know how many bananas i've got.
Would that help?

**Comment by Mace404** [comment]
I have the same with Ingress enabled. Always wants to show the equipment page.
So only works with equipment enabled.

**Comment by jimbob1001** [comment]
I have just set up this add-on & thought I won't use the equipment page so disabled it, and then got the page not found when opening the web ui. 

If I re-enable equipment then that page is the default page upon opening the web ui.

**Comment by Mace404** [comment]
Still the same issue with the latest update.

**Comment by Jeltel** [comment]
> I have just set up this add-on & thought I won't use the equipment page so disabled it, and then got the page not found when opening the web ui.
> 
> If I re-enable equipment then that page is the default page upon opening the web ui.
> 
> Edit: I think when more than one option is disabled it no longer defaults to the stockoverview page
The last reply seems almost correct. When nothing is disabled it works. When one or two things are disabled it works. When three ore more things are disabled it doesn't. It makes Equipment the default page.

**Comment by sinclairpaul** [comment]
This looks to be an upstream issue, with the good news of that a PR seems to be underway to configure the default homepage.  If you are interested the logic is at https://github.com/grocy/grocy/blob/091145c62c3dff9896b7b046e88a834c09d2daad/controllers/SystemController.php#L42

This essentially says default page is stockoverview, with some if statements.  You will always get the last in the list, so if you disable batteries the default page will be equipment.

**Comment by Jeltel** [comment]
Confirmed, if you disable functions other than battery, chores and stock it works.
