### ISSUE TITLE
Network port configuration not working on HTTPS HA instance.

### ISSUE THREAD

**Issue by MaoZ1993** [hassio-addons/addon-grocy#243]
# Problem/Motivation

down the bottom of the configuration page, the network section there is a "port forwarding" settings, allow us to map port 80 to any host port without HA ingrass.

It works fine on HTTP deployment, but once ssl set to true, the HTTPS version of Grocy is not able to access via the host port. 

## Proposed changes

I think adding another option to allow mapping 443 port will fix the issue?

**Comment by georgegebbett** [comment]
I have opened a PR #252 which allows this port to be mapped from the HA UI

**Comment by RubenKelevra** [comment]
I think that's a duplicate:

https://github.com/hassio-addons/addon-grocy/issues/208

**Comment by frenck** [comment]
HTTPS is also served over port 80, there is no 443 in this addon.
