### ISSUE TITLE
Grocy seems empty

### ISSUE THREAD

**Issue by Jeltel** [hassio-addons/addon-grocy#25]
After updating to 0.2.0 grocy seems empty.
Stock seems empty, products seem empty, users seem empty, recipes seem empty.

But everything is also there. When searching for a product in the purchage tab, the products show up. Including its stock etc.
Also the recipes, are not in the list, but are there in the gallery.

Something isn't going right here.

In all browsers by the way, including private browsing. Reproducing is probably just updating. Cannot go back myself.

**Comment by Jeltel** [comment]
After updating to 0.3.0 it has the same issues.
My stockoverview is empty. But when going to the individual stock page for a product. You can select you're  product and see the stock on the left side.
Also I cannot add any meal to the meal plan.

**Comment by frenck** [comment]
There is nothing in here that allows me to debug. Please supply logs and debug information from the add-on.

**Comment by Jeltel** [comment]
I understand. But there isn't anything in the log. I'm trying to reproduce but now i'm getting some slim application error, same as posted in: https://github.com/hassio-addons/addon-grocy/issues/27#issuecomment-500980163

Not sure what that is causing. Just updated a restored snapshot from this night.

**Comment by dthomasen** [comment]
Just got the same when upgrading to v. 3.0.1.
Seems to be related to the culture config (on my setup as least). Before upgrading it was "da", after upgrading it was changed to "en" and everything was empty.
Changing it back to "da" got everything to return.

Perhaps a whole different issue, just wanted to give my 5 cents :)

**Comment by Mace404** [comment]
Can confirm. On culture 'nl' everything seems empty.
When changing to culture 'en' everything is visible.

**Comment by Jeltel** [comment]
Same here. Now on 3.1.0.

**Comment by tjorim** [comment]
Can confirm on a clean install.
```
VM3751:1 Uncaught SyntaxError: Unexpected token l in JSON at position 1
    at JSON.parse (<anonymous>)
    at products.js?v=2.4.4:7
```
in products.js:
`'language': JSON.parse(__t('datatables_localization')),`
the 'JSON' in question:
`nl-NL`
