### ISSUE TITLE
grocy.db not in config folder

### ISSUE THREAD

**Issue by QGgWW2WhH** [hassio-addons/addon-grocy#259]
# Problem/Motivation

> I want to replace grovy.db by a backuped version from another system

## Expected behavior

> I want to be able to access / replace grocy.db in config folder

## Actual behavior

> I cannot find grocy.db - I can only access read only via snapshots

## Proposed changes

>move grocy.db to config folder (see also esphome addon)

**Comment by frenck** [comment]
> I want to be able to access / replace grocy.db in config folder

That is a Home Assistant feature request. 

See RFC: <https://github.com/home-assistant/supervisor/issues/1842>

Feel free to contribute that to the Supervisor.

**Comment by QGgWW2WhH** [comment]
Update : your can create your own add on based on the grocy addon

Just copy files of official grocy addon on GitHub in addon folder
Then copy grocy.db in /car/www/html/data
Compile and install and start
Data should be available
