### ISSUE TITLE
With Android app update the Home assistant server is not up to date anymore

### ISSUE THREAD

**Issue by WHagenauw** [hassio-addons/addon-grocy#260]
# Problem/Motivation
With Android app update (to 2.0)  the Home assistant server is not up to date anymore (still 3.1.0) App says server is not up to date

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)
To get an update from the Grocy Home assistant add on

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by MaoZ1993** [comment]
The current release version is particularly unsupported by the android app. You can try the latest Grocy addon from the EDGE repository, which contain the latest v3.1.3 grocy, works pretty stable in my environment.
