### ISSUE TITLE
401 Unauthorized through Nabu Casa Ingress on Android mobile devices

### ISSUE THREAD

**Issue by Xelinor** [hassio-addons/addon-grocy#264]
# Problem/Motivation

Trying to log into the Grocy app through Nabu Casa Ingress on an Android phone

## Expected behavior

Should be able to hit the API page on a mobile device

## Actual behavior

401 unauthorized error

## Steps to reproduce

Open https://[nabu-casa-url].ui.nabu.casa/api/hassio_ingress/[ingress-key]/api on an Android phone. Open the same URL on a PC or iPhone and it works.

**Comment by frenck** [comment]
I do not own any Android devices, so I won't be able to give an answer on this one.
