### ISSUE TITLE
404 after creating a new product from the purchase view

### ISSUE THREAD

**Issue by codingcatgirl** [hassio-addons/addon-grocy#265]
# Problem/Motivation

When going to the purchase view, scanning a barcode that doesn't have an associated product yet, and selecting to create a new product with this barcode, the following things happen:

- the product creation view is opened without the barcode, so if you click save, the barcode isn't saved
- after you click save, you get a 404 and don't comeback to the purchase page

## Expected behavior

- the barcode should be added
- you should return to the purchase screen

## Actual behavior

- the product creation view is opened without the barcode, so if you click save, the barcode isn't saved
- after you click save, you get a 404 and don't comeback to the purchase page

## Steps to reproduce

- go to the purchase view
- scan a barcode that doesn't have an associated product yet
- chose to create a new pruct with that barcode
- observe the behavior as described above

## Proposed changes

i've noticed that this is not a new bug and has been fixed previously. however, i have the latest version of the add-on installed and the bug is sadly present for me. i can only assume that some grocy update upstream broke the patch =/

**Comment by codingcatgirl** [comment]
never mind, looks like the patch was introduced after the latest version. so uh… please release a new version with that fix soon ^^;

**Comment by codingcatgirl** [comment]
I'm so sorry, looks like i have to reopen this issue. I updated the grocy add-on and this bug still persists :/

**Comment by MaoZ1993** [comment]
Issue confirmed. But it looks more likely a Grocy issue, not addon-grocy.
