### ISSUE TITLE
Patch error on startup

### ISSUE THREAD

**Issue by blue-hound** [hassio-addons/addon-grocy#270]
# Problem/Motivation

> Patch /patches/fix_braindamage.patch is not correctly applied on startup. An error is generated in the startup log.

## Expected behavior

> Patch should be applied to default.blade.php

## Actual behavior

> [cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[15:14:08] INFO: Patching Grocy to fix relative URL handling...
patching file views/layout/default.blade.php
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 15:  
[cont-init.d] grocy.sh: exited 0.

## Steps to reproduce

> I just have the default Grocy add-on installed and not modified. I have deleted the image and repulled from the command line with the 0.16.0 tag to ensure my files were correct. I have deleted the add-on and reinstalled. Same result.

## Proposed changes

> If I change +88,10 to +88,11 the patch is applied with a notice of an unexpected end. If I add a newline to the end of the last line of the patch, there are no errors present during the patch.
>
> The minor, missing newline is highlighted here along with the 11 lines in the patch.
>
> https://github.com/hassio-addons/addon-grocy/commit/7cc3aa3d19ae44111507c0033590a6c67a3bff9b?diff=split

Thanks for the great work! I don't think I caused this problem :-)

Quick edit to add that I have also used wget to get the tagged 0.16.0 file from Github with the same result.

**Comment by blue-hound** [comment]
Review still needed.

**Comment by jackyaz** [comment]
+1

**Comment by kbehren** [comment]
This seem to be what causes #273 and might be caused by #267 which seems to remove some invisible end of line character from the patch file looking at the github web view.

**Comment by kbehren** [comment]
It's merged should be in the next release.
