### ISSUE TITLE
Incorrect icon size causes misaligment

### ISSUE THREAD

**Issue by X1pheR** [hassio-addons/addon-grocy#271]
# Problem/Motivation

The width of the icon is incorrect. It's smaller then normal which causes misalignment in the overview as you can see below. 

![Screenshot_20220105-010755_Home Assistant](https://user-images.githubusercontent.com/569396/148140791-dcbf3854-652c-446e-8154-42a22dcd101d.jpg)

## Expected behavior

That there is no misalignment in the overview as it is not with the other addon icons.

## Actual behavior

See screenshot.

## Steps to reproduce

See screenshot.

## Proposed changes

Make the icon the same width as the other addon icons.

**Comment by kbehren** [comment]
Looking at it this seems to be an issue with the addon store not just the Grocy addon it's only obviously visible for grocy since the icon is taller than it is wide.
Unfortunately I'm not very good with CSS but the handling of none square icons seems to cause this.
