### ISSUE TITLE
Error when working in modals

### ISSUE THREAD

**Issue by georgegebbett** [hassio-addons/addon-grocy#273]
# Problem/Motivation

> I have noticed some strange behaviour in the latest release when working in Grocy's modals - I have encountered this issue specifically when editing stock items, and when adding ingredients to recipes, but I suspect it occurs in all modals. 

## Expected behaviour

> When you click the final save button in a modal, the action is executed and the modal closes. 

## Actual behaviour

> The action is executed, but the modal does not close. An error is thrown in the JS console:

`Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '/api/hassio_ingress/2P3VuRGiYSwW[REMOVED_BY_ME]1Nc7CCC4zIRgKsLXvU/' in a call to 'postMessage'.`

## Steps to reproduce

> Attempt to add ingredient to recipe. The error only occurs when using Grocy through Ingress and if accessed through an exposed port the behaviour is as expected. 

## Proposed changes

> Unfortunately I don't know enough about how this works to propose a solution

**Comment by kbehren** [comment]
I can confirm this behavior I'm having the same issue everything works fine through the API using grocy-android but the Add-On has issues with the modals.

**Comment by kbehren** [comment]
It's merged should be in the next release.

**Comment by georgegebbett** [comment]
Amazing! Thank your for taking the time to sort this!

**Comment by kbehren** [comment]
You're welcome. I hope the next release will be soon, no idea when they are doing that normally.

**Comment by frenck** [comment]
When I get to it 😬 

I'm looking into making it happen today, otherwise tomorrow.

**Comment by kbehren** [comment]
No pressure

**Comment by kbehren** [comment]
It would be really nice to get a release build. Constantly having to refresh the website to get changes to apply is getting really annoying.

**Comment by KyleStilkey** [comment]
Yes, I'd love to see this get fixed.

**Comment by frenck** [comment]
Ready to go, closing this issue
