### ISSUE TITLE
Reset Grocy, without losing the data for products and recipes

### ISSUE THREAD

**Issue by Jeltel** [hassio-addons/addon-grocy#29]
I've started Grocy with the first version and it works great. But updating to 0.2.0 or 0.3.0 doesn;t work. It breaks Grocy to a point where I can't use it anymore. https://github.com/hassio-addons/addon-grocy/issues/29 and https://github.com/hassio-addons/addon-grocy/issues/25. I suspect it has to do something with a setting underneath.
So I want to start again. New user, new settings, but I do not want to lose the products, stock and recipes.

I can see the data folder deep inside a snapshot of hassio. But I'm not sure what to do to get only the stock, product and recipes while ignoring the rest of the settings.

How can I do that?

**Comment by frenck** [comment]
You can fiddle with the DB if you want to, but that is not supported by the add-on.

**Comment by Jeltel** [comment]
I don't have to fiddle with the database. Grocy has an API :)
