### ISSUE TITLE
Android app API Key not working

### ISSUE THREAD

**Issue by zygote279** [hassio-addons/addon-grocy#294]
# Problem/Motivation

Trying to connect the android app to my Grocy install on Home Assistant (on RPi 4). Installed fine, but on QR code scan for API key, I get API key not working - com.android.volley.AuthFailureError.

## Expected behavior

API Connect successfully

## Actual behavior

Error above - have tried to change port after reading some posts, but can't see the option under HA Addons > Grocy > Configuration - has a single entry for port 80, but can't see option to add or modify this?

**Comment by birdwing** [comment]
There is an issue with the Grocy Android app and Grocy on Home Assistant.
They will need to fix that issue.

However, the work around is to make Grocy accessible outside of Ingres.
Under HA Addons > Grocy > Configuration. At the bottom is the network configuration.
You will need to enter a port number, usually the one I see recommended for Grocy is port 9192.

Then you can setup a reverse proxy (typically nginx proxy manager) to point your domain to that port on your HA server.
I use grocy.mydomainhere.com. Now you can access Grocy outside of Home assistant. This also fixes all the 404 not found errors that occur when using Grocy inside of ingres.

I currently have it setup this way, and the API key works just fine. The issue has to do with the android app attempting to grab the ingres ID for Grocy within HA and Grocy changed the QR code structure to so it doesn't provide enough information anymore.
