### ISSUE TITLE
Update to Grocy 3.3

### ISSUE THREAD

**Issue by Will711990** [hassio-addons/addon-grocy#295]
A new version of Grocy is arrived (https://grocy.info/changelog). 
Does it possible to update the addon ?

Thank you !!

**Comment by loganwedwards** [comment]
Is this as simple as updating the branch to checkout on the Dockerfile? I updated my iOS Grocy app that mentioned some one time db migration that needs to happen, so maybe there is more to it.

**Comment by fridtjof** [comment]
According to https://github.com/grocy/grocy#database-migrations, migrations should take place automatically on the first visit to a grocy page after updating.
