### ISSUE TITLE
Need some help with REST API plz :)

### ISSUE THREAD

**Issue by BlueBlueBlob** [hassio-addons/addon-grocy#31]
Hi.
Grocy add-on version 0.3.0
Running on hassio.
Since ingress integration, url api changed.
`curl -k -X GET "https://192.168.1.7:8123/api/hassio_ingress/rF2wUHnEuWl57NDLHjpYcZo9LGhPm7Zh4DnZs0ATay4/api/stock" -H "accept: application/json"`
Return 401 error :/
I tried with GROCY_API_KEY in header without success.
I tried with Grocy credentials and Hass credentials and longlive token, without success
No port is forwarded in Network.

If someone can help me please :)

**Comment by sinclairpaul** [comment]
Would suggest for accessing the API you expose the application on a port to duplicate the previous behaviour.

**Comment by BlueBlueBlob** [comment]
I cannot find API port.
Any idea ?
Thx @sinclairpaul

**Comment by sinclairpaul** [comment]
The REST service is exposed with the application, set the port in the Network section of the addon to what it was before, I think it was 9192.  The app will then be availiable on x.x.x.x:9192 and also via Ingress.

**Comment by BlueBlueBlob** [comment]
Thanks a lot !
