### ISSUE TITLE
External access API key

### ISSUE THREAD

**Issue by calderon67** [hassio-addons/addon-grocy#315]
I do not know if it is a problem, but how can I generate an external access to grocy to use the android APK? Is it possible?

**Comment by ITensEI** [comment]
Wrench in top right corner. Select Manage API Keys and Add a new one.
![image](https://user-images.githubusercontent.com/9561099/199102216-fceb832b-5d92-4242-a883-c1c4d342b2c4.png)

**Comment by DarS007** [comment]
@ITensEI - nope, I am afraid. The API key is indeed being generated and visible in the Grocy web interface, but when the Android app [grocy-android](https://github.com/patzly/grocy-android) tries to read it, fails. The error message reads: _Not a QR code with a long-lived access token from Home Assistant._

![20221113-grocy_app-issue](https://user-images.githubusercontent.com/31861059/201515357-67cb7863-e021-4fea-9881-45afcf492c35.jpg)
How we can troubleshoot it further? Is this the issue with Grocy add-on, or with the Grocy Android app?
Regards,
-DarS

**Comment by blowk** [comment]
Is it possible to manually enter the data?

Does anyone know what the address and port to be used (server URL: https://mydomain.duckdns.org/grocy_hassio)? I cannot figure it out.
