### ISSUE TITLE
Can't add items

### ISSUE THREAD

**Issue by NathanSalapat** [hassio-addons/addon-grocy#325]
# Problem/Motivation

Grocy doesn't let me save any inventory through the inventory or purchase screen.

## Expected behavior

Clicking okay should add the data to the database

## Actual behavior

Mouse cursor spins for a while then nothing happens

System Information:
Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

Running on a Raspberry Pi

**Comment by NathanSalapat** [comment]
Hmm, very interesting, I think I may have found a solution. I changed all the config options back to default and now it is working. I'll try and work through which setting breaks it.

**Comment by phoniclynx** [comment]
I raised this issue here: https://github.com/grocy/grocy/issues/2101#event-8176088477
The devs of Grocy say that is a Home Assistant error.. so something is wrong with the addon here

**Comment by NathanSalapat** [comment]
I never did actually figure out what was causing the issue. I originally didn't plan on tracking expiration dates, locations, or what store things were purchased from. With the troubles I was having though I decided to track that information as well.
