### ISSUE TITLE
Feature request: Shop/Store and department

### ISSUE THREAD

**Issue by loovanloon** [hassio-addons/addon-grocy#326]
Please add the following functionality to the Shopping list:
- Store / Shop: where you buy your grocery item
- Department/ Route: the department (eg Fresh vegetables , Meat, Dairy, Frozen, Cookies) in a store where you can find the item on your shopping list. This can simply be a integer or a string ( that starts with a number : 01 Vegies, 02 Bread, 03 Soups & Herbs etc)

As a user I want to group and sort my shopping list items by Store and within the Store by Department because it will make my shopping far more efficient: It will give an efficient route for my shopping. 

As a user I want be able to set the order of the Shops and Department as a setting, e.g. 
Shops: 01 supermarket A, 02 Butcher, 03 Bakery, 
Departments: 01 Vegies, 02 Bread, 03 Soups & Herbs

As a user I want to be able to have my shopping list presented grouped by and order by shop and department. 

As a user I want to be able to assign a default shop and department to each common stock item so that I do not have to input this info every time I put a stock item on my shopping list. 

As a user I want to be able to override the default store and department when I put a stock item on my shopping list.

**Comment by frenck** [comment]
Hi there @loovanloon 👋 

This is the add-on. Add-ons in Home Assistant, wrap existing applications, and make them manageable/usable inside Home Assistant. In the end, they use the original applications (which are not developed by the add-on itself).

In this case, the add-ons wraps the Grocy application. If you want new features for Grocy itself, it is best to report that with the Grocy project. Once added, the add-on will get it too.

You can information and resources on the Grocy project here: <https://grocy.info/>

Closing the issue on this end, as (from an add-on perspective), it isn't actionable.

Nevertheless, Happy Holidays! 🎄 

../Frenck

**Comment by loovanloon** [comment]
Clear message Frenck! Thank you for your prompt reply. Happy holidays. Met vriendelijke groet,Ton van LoonOp 22 dec. 2022 om 16:24 heeft Franck Nijhof ***@***.***> het volgende geschreven:﻿
Hi there @loovanloon 👋
This is the add-on. Add-ons in Home Assistant, wrap existing applications, and make them manageable/usable inside Home Assistant. In the end, they use the original applications (which are not developed by the add-on itself).
In this case, the add-ons wraps the Grocy application. If you want new features for Grocy itself, it is best to report that with the Grocy project. Once added, the add-on will get it too.
You can information and resources on the Grocy project here: https://grocy.info/
Closing the issue on this end, as (from an add-on perspective), it isn't actionable.
Nevertheless, Happy Holidays! 🎄
../Frenck
