### ISSUE TITLE
Use different URLs for local and remote/external

### ISSUE THREAD

**Issue by sticilface** [hassio-addons/addon-grocy#328]
# Problem/Motivation

I would like to use the native app grocy and not the embedded Lovelace version. The home assistant app allows 2 URLs, one when on local lan and one when external.  As it stands I can generate api keys but the ip address is local only. If I hard code my external is address it works externally but not locally. This is because I use VPN port forwarding as my internet provider uses CGNAT which makes things complicated, and the fixed external ip does not work locally. 

## Expected behavior

specify 2 addresses. One for LAN and a second for external networks similar to home assistant. 

![4A659E11-EEC9-4BE0-A78A-2FD7D9339CA2](https://user-images.githubusercontent.com/10061736/209427879-0695b153-740e-4f8e-8081-603eace1b718.jpeg)

**Comment by frenck** [comment]
Hi there!

This is the issue tracker for the Grocy add-on, we don't develop Grocy, nor do we develop the Grocy app. This is a feature you should request @ the Grocy project. We cannot help you with that.

Thanks 👍 

../Frenck
