### ISSUE TITLE
exterior access ?

### ISSUE THREAD

**Issue by schumi2309** [hassio-addons/addon-grocy#329]
Hello,
I installed grocy in my Home assistant and everything works fine. to complete I installed the grocy application on my iphone ios. with the server address http://192.168.0.*:9192 with the api key by checking home assistant
the problem is that I don't have access if I'm outside. do i have to change something in the server?
How to get access to the outside?
Thank you

**Comment by frenck** [comment]
You can enable external access to the add-on by assigning a port to it in the add-on network settings in Home Assistant.

../Frenck

**Comment by schumi2309** [comment]
So how do I access my shopping list from my grocy home assistant on my iphone outside via the grocy app?

**Comment by frenck** [comment]
By using that port?

**Comment by schumi2309** [comment]
in the grocy app, I put:

http://192.168.0.12:9192

But it does not work

**Comment by frenck** [comment]
If you go to Grocy using your normal browser (not the app):

http://192.168.0.12:9192/

Does that work?

**Comment by schumi2309** [comment]
no, it doesn't work

**Comment by frenck** [comment]
could you share a screenshot on how you configured it on your end in Home Assistant in the add-on configuration? I will try to re-produce it with that on my end.

**Comment by schumi2309** [comment]
this ? 

![Capture d’écran 2023-01-06 à 11 34 38](https://user-images.githubusercontent.com/47976917/210990494-4d209516-0c97-45a9-a275-77194780797b.png)

![Capture d’écran 2023-01-06 à 11 34 46](https://user-images.githubusercontent.com/47976917/210990585-fc7390e9-d903-43d5-ab8e-b6ff7a7ac290.png)

**Comment by frenck** [comment]
I've configured it locally the same as you did above in the screenshots, and I can access Grocy on `http://test.local:9192/login` from my local network after I restarted the add-on.

In this case, of course, test.local is my instance of HA (which is in your case an IP address as it seems).

I cannot reproduce the issue you are reporting. Is there anything in the logs?

../Frenck

**Comment by frenck** [comment]
> but when i'm outside it doesn't work

yeah makes sense, `192.168.0.12` is a local address... which is local... as in not remote. You need to use your public address and make sure you make the port available in that case too.

However, that is not an limitation off the add-on, nor it is in scope for the add-on. This is about configuring your network. I can't help you with that.

../Frenck
