### ISSUE TITLE
Unable to Use Meal Plan

### ISSUE THREAD

**Issue by bruhautomation** [hassio-addons/addon-grocy#33]
Hello! Thanks for your great work on this add-on!

I'm unable to add meals in the meal plan tab. I believe this is done by clicking the [+] buttons near the date in the calendar view. I do not get any popup when I click those buttons. 

![image](https://user-images.githubusercontent.com/14144928/60347329-0b43b000-998b-11e9-8e81-bf5d408b1cd8.png)

This shows in the debug log:

`2019/06/28 09:50:21 [error] 990#990: *9 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: hintId in /data/grocy/viewcache/79ce{redacted_long_string}.php on line 11" while reading response header from upstream`

Cheers!

**Comment by frenck** [comment]
Interesting @bruhautomation, I'll look into that. It should not crash on a notice.

**Comment by sinclairpaul** [comment]
I believe I can duplicate this, and in my case its the currency config.  The currency should be the ISO4217 code checking the docs, can you try setting ```"currency": "USD"``` in your config?

**Comment by bruhautomation** [comment]
@sinclairpaul, wow, nice catch! Switching to `"currency": "USD"` solved this issue for me. Thanks for the tip!

**Comment by frenck** [comment]
I'm re-opening this since it is an issue. One should not be able to get the add-on in a broken state.

**Comment by frenck** [comment]
PR implementing a fix is tracked in #34

**Comment by frenck** [comment]
Fixed in #34, will be enforced in the next release.
