### ISSUE TITLE
Where to copy a backup of grocy.db after a problem

### ISSUE THREAD

**Issue by Xiondewah** [hassio-addons/addon-grocy#330]
I had an issue where the quantity units weren't showing up and read that it was likely due to a corruption.  So I took a backup and have extracted it to find the grocy.db and reinstalled Grocy.

Where do I need to copy the db file back to please?  I'm running this on a RPi4.

Thanks.

**Comment by frenck** [comment]
> Where do I need to copy the db file back to please?

Nowhere, these parts aren't generally accessible. Please use the backup and restore the functionality of Home Assistant instead.

../Frenck
