### ISSUE TITLE
enable Barcode - 2D Datamatrix

### ISSUE THREAD

**Issue by meistermolli** [hassio-addons/addon-grocy#333]
# Problem/Motivation
Is there a way to Enable the 2D Data matrix like the Original Grocy?

[https://github.com/grocy/grocy/releases](url) Version 3.1.0

> The used barcode type can be configured via the config.php option GROCYCODE_TYPE:
> 1D (default) will produce a Code128 1D barcode (supported by the integrated camera barcode scanner)
> 2D will produce a DataMatrix 2D barcode (currently not supported by the integrated camera barcode scanner, but can be probably printed smaller)

Is there a Way to enable the label Printer inside the Addon?

Maybe its possible to integrate an Option inside the Configuration Page of the Addon?

Thanks

**Comment by kguy18** [comment]
I tried to do this using the yaml config option in the configuration option and no dice, no matter where I put it. I too would like to change mine to 2D.
