### ISSUE TITLE
async_setup_platforms warning

### ISSUE THREAD

**Issue by cdouet** [hassio-addons/addon-grocy#336]
# Problem/Motivation

The following warning is logged on my home assistant yellow setup:
Logger: homeassistant.helpers.frame

Source: helpers/frame.py:77
First occurred: 4:15:53 PM (1 occurrences)
Last logged: 4:15:53 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for grocy using this method at custom_components/grocy/__init__.py, line 52: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)_

## Expected behavior

No warning

## Actual behavior

This occurs at startup but grocy is working fine

## Steps to reproduce

In order to reproduce this warning, a simple reboot is enough

## Proposed changes

No idea

**Comment by sinclairpaul** [comment]
`Please report issue to the custom integration author for grocy using this method at custom_components/grocy/init.py`

This is a custom integration you have installed in Home Assistant generating the error, it isn't related to the addon itself.
