### ISSUE TITLE
RON is not supported as a currency

### ISSUE THREAD

**Issue by johnflorin** [hassio-addons/addon-grocy#35]
# Problem/Motivation

I tried to configure the addon to work with RON as a currency and it would not save products properly or allow me to add to Inventory.

## Expected behavior

I add a new product and get the green confirmation in the corner and I can then add it to the Inventory.

## Actual behavior

When confirming the adding of a new product, the final step results in a Page Not Found error and when I try to use that product to add it to the Inventory, the green confirmation is grayed out even though I filled in all the fields. It works fine if I use the addon with USD. 

## Steps to reproduce

Input "currency": "RON" in the addon config and try to add a product and use it in the Inventory.

## Proposed changes

Either add support for all ISO 4217 currencies, or change the documentation, which right now says:

**_Option: currency_**

**_Determines the currency as displayed in the Grocy interface, specified by the ISO4217 three digit currency code.

Examples: USD, CAD, GBP or EUR._**

**Comment by sinclairpaul** [comment]
Can you confirm if this only occurs when using Ingress, i.e. if you expose the port for the addon and use that, it functions fine?

This is the behavior that I am seeing.

**Comment by johnflorin** [comment]
This seems to be the case, although I didn't expose a specific port just for the addon...when using the Ingress link, I get a 404 after adding a product, when using my HA DuckDNS link, it works fine and with any currency in the config as well (in both cases I am accessing the addon from the side panel as configured via "Show in sidebar").
