### ISSUE TITLE
Grocy error after upgrading Home Assistant to 2023.6.1

### ISSUE THREAD

**Issue by ebolly** [hassio-addons/addon-grocy#369]
Hello Franck,

Seems to be an issue related to new Python release, grocy is not starting

Setup failed for custom integration grocy: Requirements for grocy not found: ['pygrocy==1.4.1'].

**Comment by ebolly** [comment]
Unable to install package pygrocy==1.4.1: ERROR: Cannot install pygrocy==1.4.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by andreklug** [comment]
same issue for me after updating

**Comment by frenck** [comment]
> Setup failed for custom integration grocy: Requirements for grocy not found: ['pygrocy==1.4.1'].

This is not an error message from the add-on, but from Home Assistant itself. It is not even add-on related. I think you are mixing up the Grocy custom integration with the Grocy add-on.

Closing the issue on this end, as it is not related.

../Frenck
