### ISSUE TITLE
Addon still fails to upload bigger files.

### ISSUE THREAD

**Issue by Maczuga** [hassio-addons/addon-grocy#38]
# Problem/Motivation

> Uploading a 3.31MB attachment to an equipment causes a "Maximum request body size 1048576 exceeded, actual body size 1053380" error. Uploading ~10MB results in 502 - bad gateway.

## Expected behavior

> Attachment should be uploaded correctly.

## Actual behavior

> Same as problem/motivation.

Result of uploading a 3.31MB file
![image](https://user-images.githubusercontent.com/544349/61184375-59280b80-a64d-11e9-829a-f9300559d1d1.png)

Result of uploading a 10MB+ file
_removed due to private domain name listed_

## Steps to reproduce

1. Create an equipment or edit an existing one
2. Try to attach a bigger PDF file (in my case it's just 3.31 MB)
3. Error pops up

## Proposed changes

> Ensure, that nginx config is properly executed, because it looks right now, that those values from commit https://github.com/hassio-addons/addon-grocy/commit/839d3ff850e9378ab9bbe0d1d1e8627336f26996 are being ignored on clean install.
I also tried removing the docker image/volumes for grocy after uninstalling from hassio - same issue happens.

I am using 0.31 version of addon.

**Comment by sinclairpaul** [comment]
Is this via Ingress?, can you validate with the addon exposed using a port?  It would also be good to see the addon logs for this request.

**Comment by Maczuga** [comment]
Yes, this is via Ingress. 

Actually when using addon via exposed port it works fine. 

There were no errors in logs about it when using Ingress. Only some trace messages about functions that were used + requests, but no errors (log was set to trace for that). Logs attached below (log_level = trace).

[logs.txt](https://github.com/hassio-addons/addon-grocy/files/3390010/logs.txt)

**Comment by sinclairpaul** [comment]
Thanks, it is what I was expecting, Ingress adds an additional Proxy, which I am guessing is blocking the upload.  The error as such isn't with the addon, but upstream with Hass.io.

**Comment by frenck** [comment]
Wait, the error message on the second screenshot shows Apache. We don't use Apache.

However, we do accept file uploads up to 64Mb.

I suspect Apache is hanging up on the body size.

**Comment by Maczuga** [comment]
Yup, closing this issue as it's not about this addon after all, issue remains somewhere in my local apache proxy. I'll post results if I find any fix for that for any person in need in future.
