### ISSUE TITLE
Grocy server update

### ISSUE THREAD

**Issue by mike9449** [hassio-addons/addon-grocy#387]
I can't use the Iphone Grocy app because it only works with Grocy Server 4.0
If I try to access with actual server "API error" appear

**Comment by 1st-BrainStormer** [comment]
Android App also has issues with the old server version. Like Recipe ingredients list can contain wrong fulfillment information  etc.  Latest Version is 4.03

**Comment by bbccdd** [comment]
The current 3.x version also breaks other tools like https://github.com/supergeorg/Grocy-SwiftUI/issues/181. So we'll just have to be patient. 

PS One can subscribe to #380 so you'll know it once merged.

**Comment by frenck** [comment]
Shipped here: <https://github.com/hassio-addons/addon-grocy/releases/tag/v0.20.0>
