### ISSUE TITLE
Proposal for group or categories for chors

### ISSUE THREAD

**Issue by snuf1991** [hassio-addons/addon-grocy#406]
# Problem/Motivation

I have a proposal for making it possible to sort the chores by room or area inspired by the app Tody.

## Expected behavior

The possibility to sort the chres by room and see which rooms needs most attention.

## Actual behavior

I can't seem to find this option at the moment.

## Steps to reproduce

I don't know how it could be programmed, but maybe just simple categories made by rooms.

## Proposed changes

This will make it easier to see which room is needing most attention.

**Comment by sinclairpaul** [comment]
The addon installs existing software, you would need to log your feature request at <https://github.com/grocy/grocy>
