### ISSUE TITLE
Integration not found: grocy

### ISSUE THREAD

**Issue by stefancvetkovic** [hassio-addons/addon-grocy#41]
I added into my config file

`grocy:
  url: "http://hassio.local:8123/api/hassio_ingress/xJNwv4F8SBerwLRpJo5ujxNmZb1t39MuWrI-C3fzKxc/api"
  api_key: "YX6RjEDOY9ecClHPKFLEFl2oiV3OyhLc123437637"
  sensor:
    - enabled: true`

and when I check out my config it says `Integration not found: grocy`

**Comment by frenck** [comment]
I build the add-on, not the custom component/integration.
Please report any issues with the repository/author of that integration.
