### ISSUE TITLE
Date Field Bug and Undo Task Error

### ISSUE THREAD

**Issue by arretx** [hassio-addons/addon-grocy#42]
# Problem/Motivation

After completing a task, I checked the "show done" checkbox to re-enable the task.  Upon clicking the circle arrow icon to re-enable the task, I was met with a strange error screen.  The task was undone as expected, and after refreshing the page it all looked okay, except that the due date had been change to January 1, 1970.

So, I edited the due date field and it wouldn't allow me to save because it couldn't detect that a date was selected.  

It turns out there was some sort of erroneous space in front of the date, which when deleted, activated the Save button and all was well.

**Comment by sinclairpaul** [comment]
This is likely an upstream issue with the application, can you post the addon logs for when you had the error so this can be determined.  I cannot duplicate the behaviour (as a note I see the default date on undoing a task with no due date set, which makes sense, but again would be the application logic).
