### ISSUE TITLE
Grocy won't start - Failed Opening /var/www/grocy/data/config.php

### ISSUE THREAD

**Issue by CrackPT** [hassio-addons/addon-grocy#43]
# Problem/Motivation

> Grocy starts properly but it shows an error when trying to access it
>Running Hass.io on docker (0.97.2) on a Debian environemnt and all the add-ons have worked so far, apart from this one
When running Grocy, it starts without any issues, but then I get this message when accessing the UI:

**Outputed Error**
`2019/08/19 12:31:55 [error] 506#506: *11 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/grocy/data/config.php): failed to open stream: Permission denied in /var/www/grocy/app.php on line 40PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/grocy/data/config.php' (include_path='.:/usr/share/php7') in /var/www/grocy/app.php on line 40" while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-grocy.local.hass.io, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "<REMOVED>", referrer: "https://<REMOVED>/a0d7b954_grocy"`

**Config**
`{
  "culture": "en",
  "currency": "GBP",
  "features": {
    "batteries": true,
    "calendar": true,
    "chores": true,
    "equipment": true,
    "recipes": true,
    "shoppinglist": true,
    "stock": true,
    "tasks": true
  },
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "debug"
}`

> I checked the addons/data folder and I can see that the config.php file is there, I've been looking at the GirHub repo to understand what could be wrong, but I couldn't find the reason. I can see that that folder has different permissions from all the others in the addons folder (not sure if the startup process is doing it and maybe messing up with the permissions)

## Expected behaviour

> To be able to access to Grocy

## Actual behaviour

> Blank page and error logged as above

## Steps to reproduce

> Installed Grocy using hassio and run with the config provided above

**Comment by sinclairpaul** [comment]
Could you please post the full addon startup log?  Is the behaviour the same if the addon is removed and re-installed?

**Comment by CrackPT** [comment]
Hi @sinclairpaul

Thank you for your message

Yes, the behaviour is the same. I've tried to remove the add-on, remove the docker image from my repository to force it to load a new one, removed all the grocy related folders and still no luck

Here you have the logs:
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0. [s6-init] ensuring user provided files have correct perms...exited 0. [fix-attrs.d] applying ownership & permissions fixes... [fix-attrs.d] 01-grocy: applying... [fix-attrs.d] 01-grocy: exited 0. [fix-attrs.d] done. [cont-init.d] executing container initialization scripts... [cont-init.d] 00-banner.sh: executing... ----------------------------------------------------------- Hass.io Add-on: Grocy ERP beyond your fridge! A groceries & household management solution for your home ----------------------------------------------------------- Add-on version: 0.3.1 You are running the latest version of this add-on. System: Debian GNU/Linux 9 (stretch) (amd64 / qemux86-64) Home Assistant version: 0.97.2 Supervisor version: 181 ----------------------------------------------------------- Please, share the above information when looking for help or support in, e.g., GitHub, forums or the Discord chat. ----------------------------------------------------------- [cont-init.d] 00-banner.sh: exited 0. [cont-init.d] 01-log-level.sh: executing... Log level is set to DEBUG [cont-init.d] 01-log-level.sh: exited 0. [cont-init.d] grocy.sh: executing... [11:38:43] DEBUG: Symlinking data directory to persistent storage location... [cont-init.d] grocy.sh: exited 0. [cont-init.d] nginx.sh: executing... [cont-init.d] nginx.sh: exited 0. [cont-init.d] done. [services.d] starting services [services.d] done. [11:38:43] INFO: Starting PHP-FPM... [11:38:44] INFO: Starting NGinx.... 2019/08/19 11:38:56 [error] 506#506: *1 FastCGI sent in stderr: "PHP message: PHP Warning: require_once(/var/www/grocy/data/config.php): failed to open stream: Permission denied in /var/www/grocy/app.php on line 40PHP message: PHP Fatal error: require_once(): Failed opening required '/var/www/grocy/data/config.php' (include_path='.:/usr/share/php7') in /var/www/grocy/app.php on line 40" while reading response header from upstream, client: 172.X.X.X, server: a0d7b954-grocy.local.hass.io, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "<REMOVED>", referrer: "https://<REMOVED>/a0d7b954_grocy"
`

**Comment by sinclairpaul** [comment]
Thanks, that log looks fine (apart from the last error).  Can you uninstall the addon, reinstall and post the addon startup (with debug level) and also the supervisor log.  It is almost as if the file permissions step is failing.

Also you mentioned you had no issues with other addons, may I ask which others you installed ok?

**Comment by CrackPT** [comment]
*Logs from a fresh install*
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-grocy: applying... 
[fix-attrs.d] 01-grocy: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.3.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 9 (stretch)  (amd64 / qemux86-64)
 Home Assistant version: 0.97.2
 Supervisor version: 181
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[13:52:05] DEBUG: Data directory not initialized, doing that now...
[13:52:05] DEBUG: Symlinking data directory to persistent storage location...
[cont-init.d] grocy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:52:05] INFO: Starting PHP-FPM...
[13:52:05] INFO: Starting NGinx....
2019/08/20 13:54:04 [error] 464#464: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/grocy/data/config.php): failed to open stream: Permission denied in /var/www/grocy/app.php on line 40PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/grocy/data/config.php' (include_path='.:/usr/share/php7') in /var/www/grocy/app.php on line 40" while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-grocy.local.hass.io, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "<REMOVED>", referrer: "https://<REMOVED>/a0d7b954_grocy"
[20/Aug/2019:13:54:04 +0100] 500 62.249.252.196, 172.XXX.XXX.XXX, 172.XXX.XXX.XXX(172.XXX.XXX.XXX) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3872.0 Safari/537.36 Edg/78.0.244.0)
```

*Logs from supervisor*
```
19-08-20 12:51:18 INFO (SyncWorker_25) [hassio.docker.interface] Stop addon_a0d7b954_grocy application
19-08-20 12:51:18 INFO (SyncWorker_25) [hassio.docker.interface] Clean addon_a0d7b954_grocy application
19-08-20 12:51:22 INFO (SyncWorker_7) [hassio.docker.interface] Remove image hassioaddons/grocy-amd64 with latest and v0.3.1
19-08-20 12:51:22 INFO (MainThread) [hassio.addons.addon] Remove add-on data folder /data/addons/data/a0d7b954_grocy
19-08-20 12:51:22 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-08-20 12:51:22 INFO (MainThread) [hassio.ingress] Update Ingress as panel for a0d7b954_grocy
19-08-20 12:51:22 INFO (MainThread) [hassio.addons] Add-on 'a0d7b954_grocy' successfully removed
19-08-20 12:51:48 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/a0d7b954_grocy
19-08-20 12:51:48 INFO (SyncWorker_0) [hassio.docker.interface] Pull image hassioaddons/grocy-amd64 tag 0.3.1.
19-08-20 12:51:49 INFO (MainThread) [hassio.addons] Add-on 'a0d7b954_grocy' successfully installed
19-08-20 12:52:04 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/grocy-amd64 with version v0.3.1
19-08-20 12:52:04 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_grocy
19-08-20 12:53:52 INFO (MainThread) [hassio.ingress] Update Ingress as panel for a0d7b954_grocy
```

ATM, I am running

- AdGuard Home
- Check Home Assistant Configuration
- ESPHome
- Grafana
- Grocy **issues**
- Home Panel
- InfluxDB
- Mosquitto broker
- Node-RED
- Portrainer
- Visual Studio Code
- zigbee2mqtt

It is indeed very weird the fact that nothing states an issue with the installation process.

**Comment by CrackPT** [comment]
Just to add to my previous comment, these are the permissions at the file-system level

```
$ ls -la data/a0d7b954_grocy/
total 85
drwxrws---+  3 root             Users             4 Aug 20 13:52 .
drwxrws---+ 15 root             Users            15 Aug 20 13:51 ..
drwxr-xr-x+  4 systemd-timesync systemd-journal   6 Aug 20 13:52 grocy
-rw-rw----+  1 root             Users           334 Aug 20 13:52 options.json
```

```
ls -la data/a0d7b954_grocy/grocy/
total 106
drwxr-xr-x+ 4 systemd-timesync systemd-journal  6 Aug 20 13:52 .
drwxrws---+ 3 root             Users            4 Aug 20 13:52 ..
-rw-r--r--+ 1 systemd-timesync systemd-journal 36 Aug 20 13:52 config.php
-rw-r--r--+ 1 systemd-timesync systemd-journal 34 Aug 20 13:52 .gitignore
drwxr-xr-x+ 2 systemd-timesync systemd-journal  4 Aug 20 13:52 plugins
drwxrwx---+ 2 systemd-timesync systemd-journal  2 Aug 20 13:52 viewcache
```
