### ISSUE TITLE
Grocy code at 4.2 but hass addon is 4.0.3

### ISSUE THREAD

**Issue by helicalchris** [hassio-addons/addon-grocy#454]
# Problem/Motivation

I am wondering if there is going to be an update to the addon as Grocy is v4.2 but addon is running 4.0.3.  This matters to me as there is a bug in the meal planner that was fixed in later versions.  I dont really want to migrate from addon to standalone if i can avoid it!

## Expected behavior

New version based on new Grocy version

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

pull of grocy 4.2 into the addon

**Comment by sinclairpaul** [comment]
It's already merged <https://github.com/hassio-addons/addon-grocy/pull/434>

It just needs a release for which there are no defined timescales.  As this isn't an issue will close.

**Comment by helicalchris** [comment]
Fair enough to close it but if the pull request is there (I saw it but assumed after this time there was an issue blocking it) does that mean that this add on is no longer actively maintained?  Please don't mistake this for an assumption that you aren't busy and buried in other stuff, it's a genuine question as in the past I know that releases have been pretty swift and I'd rather plan a move to a standalone Grocy now than get caught out with a major issues later and find I need to!  
Thanks! 
Chris
