### ISSUE TITLE
[Feature Request] Real Ingress auto login using home assistant X-Remote-User headers

### ISSUE THREAD

**Issue by LelouBil** [hassio-addons/addon-grocy#458]
# Problem/Motivation

To map grocy users to home assistant users

## Expected behavior

Click on Grocy in the sidebar and be automatically logged-in with a user specific to the hass user I'm currently logged in to

## Actual behavior

Either the grocy login page, or the default user configured in the addon config

## Proposed changes

Use these headers https://developers.home-assistant.io/docs/add-ons/security/#authenticating-a-user-when-using-ingress
And find out a way for grocy to auto login with headers or auto create users.

**Comment by G-nn-r** [comment]
This would be a great improvement. Right now, the setup is not quite intuitive.
