### ISSUE TITLE
404 Page Not Found when Equipment and Batteries disabled

### ISSUE THREAD

**Issue by jptrsn** [hassio-addons/addon-grocy#51]
# Problem/Motivation

Attempting to open the add-on when both Equipment and Batteries are disabled results in a 404 not found message logged, and the UI will not load. With either one enabled, the UI loads properly. I have cleared the cache and tried incognito, without success. Looks like #24 did not resolve this particular configuration issue, and it is unrelated to #30 as I meet the minimum system requirements. Alternatively, I saw some mention of a setting for the page to use when attempting to load, but that setting does not appear in the read me file or example configuration.

According to #37 this should have been resolved in a previous release.

I am running Home Assistant version 0.99.3.
![image](https://user-images.githubusercontent.com/5185267/66217625-a8526b00-e695-11e9-835a-2a52e06c44ec.png)
![image](https://user-images.githubusercontent.com/5185267/66217638-ad171f00-e695-11e9-9721-223bc7a6cf17.png)

## Expected behavior
I should be able to open the add on without the requirement for Equipment or Batteries, as I do not intend to use those features.

## Actual behavior
When both those features are disabled, the UI returns a 404 Page Not Found.

![image](https://user-images.githubusercontent.com/5185267/66217649-b1dbd300-e695-11e9-8cb0-2b12bc52fd21.png)

## Steps to reproduce
Use the following configuration and attempt to load the add-on.
```json
{
  "culture": "en",
  "currency": "CAD",
  "features": {
    "batteries": false,
    "calendar": false,
    "chores": true,
    "equipment": false,
    "recipes": true,
    "shoppinglist": false,
    "stock": false,
    "tasks": true
  },
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "info"
}
```

Resulting logs show the following:
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-grocy: applying... 
[fix-attrs.d] 01-grocy: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
> 
-----------------------------------------------------------
> Hass.io Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
> 
-----------------------------------------------------------
> Add-on version: 0.3.2
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.99.3
 Supervisor version: 189
> 
-----------------------------------------------------------
> Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
>
 -----------------------------------------------------------
>[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[cont-init.d] grocy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:50:37] INFO: Starting PHP-FPM...
[10:50:40] INFO: Starting NGinx....
[04/Oct/2019:10:50:48 -0400] 302 192.168.1.1, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36)
[04/Oct/2019:10:50:48 -0400] 404 192.168.1.1, 172.30.32.1(172.30.32.2) GET /equipment HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36)

**Comment by sinclairpaul** [comment]
The release isn't out yet with the fix.  It's currently in the dev branch.
