### ISSUE TITLE
Any chance to update the add-on to ️Grocy to v2.5.2?

### ISSUE THREAD

**Issue by gcorgnet** [hassio-addons/addon-grocy#57]
Hi,

Thanks a lot for putting this together!
I can see most of the work has been done to update this add-on to the latest version of Grocy but these chances haven't been released (possibly due to failed build, back in early October

Is there any chance that this could be fixed up?

Thanks,

Guillaume

**Comment by frenck** [comment]
It is on the short list, however, I have had a busy season with a lot of life changing things going on. I expect to be back on track soon.

**Comment by llewy** [comment]
So Frenck, you're part of the Nabu Casa team now, plenty of time to fix the upgrade! ;-)

Just kidding!
