### ISSUE TITLE
"Maximum request body size 1048576 exceeded, actual body size 1049808"

### ISSUE THREAD

**Issue by snipes040** [hassio-addons/addon-grocy#59]
# Problem/Motivation
When uploading a pdf file, I still get the same error no matter what size. Error: "Maximum request body size 1048576 exceeded, actual body size 1049808"

> (Why the issue was filed)

## Expected behavior
It should upload the PDF file and save the entry.
> (What you expected to happen)

## Actual behavior
Error: "Maximum request body size 1048576 exceeded, actual body size 1049808"
> (What actually happened)

## Steps to reproduce
Upload a PDF file bigger than 1MB on Grocy 0.4.0
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Additional Details:
- Latest version of Hassio 0.103.5
- Running on a docker host
- Hassio Supervisor 193
[grocylogs.txt](https://github.com/hassio-addons/addon-grocy/files/4010502/grocylogs.txt)

**Comment by jackwilsdon** [comment]
See #38 and #47 - it looks like this may be a problem with Ingress. Have you tried exposing Grocy on its own port and seeing if the same issue occurs?

**Comment by snipes040** [comment]
Hmm ok I haven't tried that yet as my system is on docker behind my traefik reverse proxy so I'll need to figure out how to expose the addon via SSL.  Thanks for the links to the #38 issue.  is this in the works of being fixed do you know?

**Comment by jackwilsdon** [comment]
I've not found any mention of this being in the works. Seems like this issue could be in Home Assistant itself - will need more testing to confirm it (I might get round to this at some point, but it'd be great if someone else could do some testing).

https://github.com/home-assistant/home-assistant/blob/00dc7216093abd099b1e4a58a14876cc9ed2896e/homeassistant/components/hassio/ingress.py#L123

Looks like the aiohttp client Home Assistant is using to forward requests to the right ingress container has a default max request size of 1024^2, which happens to be 1048576.

**Comment by cerebrate** [comment]
Yeah, this is an ingress problem. (Just reported it here: https://github.com/home-assistant/hassio-supervisor/issues/1420 before finding this.) As a workaround, you can upload just fine to grocy by accessing on its port 9192.

That said, it's not a complete fix. While I was poking around the containers looking for the issue, I found that despite the last two lines in https://github.com/hassio-addons/addon-grocy/blob/master/grocy/rootfs/etc/php7/conf.d/99-grocy.ini , the post_max_size and upload_max_filesize weren't being set to 64M by PHP (checked by running phpinfo() in a test file). I had to amend those lines to just

```
post_max_size = 64M
upload_max_filesize = 64M
```

to get it to work.

**Comment by cerebrate** [comment]
Fix inbound:

- https://github.com/home-assistant/hassio-supervisor/pull/1423
- https://github.com/home-assistant/home-assistant/pull/30608

**Comment by frenck** [comment]
Yep!

**Comment by frenck** [comment]
Fix has been applied to the Home Assistant Supervisor.
