### ISSUE TITLE
How do I backup Grocy?

### ISSUE THREAD

**Issue by RonSpawnson** [hassio-addons/addon-grocy#60]
I'm worried about SD card failure, any recommendations how I can backup my Grocy data? Sounds like Grocy generally stores data in the /data directory, where do I find that for this Hassio plugin?

**Comment by frenck** [comment]
Hass.io provides Snapshots to backup the system (including add-ons and their data).

**Comment by RonSpawnson** [comment]
Perfect, and easy to use. Thanks for the quick response frenck!

**Comment by frenck** [comment]
No problem sir!
