### ISSUE TITLE
Wrong setting in tweaks after update

### ISSUE THREAD

**Issue by ministryofsillywalks** [hassio-addons/addon-grocy#62]
# Problem/Motivation

After upgrading the Addon wouldn't start.
Looking in the logs I get the following error:
Add-on a0d7b954_grocy have wrong options: Missing option stock_product_freezing in tweaks.
Adding that line to the config was an easy fix to the problem but I'm guessing this wasn't supposed to happen in the first place ;)

## Expected behavior

Addon starting

## Actual behavior

Addon not starting

## Steps to reproduce

Upgrade to 0.6.0

## Proposed changes

Add
    "stock_product_freezing": true
to the standard config

**Comment by darkcloud784** [comment]
This is the same issue I was having, I just didn't know where to look in the logs to find the correct information. Thanks. Hope this gets resolved.

**Comment by frenck** [comment]
It is in the standard configuration:

<https://github.com/hassio-addons/addon-grocy/blob/master/grocy/config.json#L43>

This is not a behavior I can control from the add-on end.
The only solution is to add it manually to the add-on configuration manually.

For myself, I should be more aware of this and add it to the changelog/release notes.
