### ISSUE TITLE
Equipment Tab Improvement

### ISSUE THREAD

**Issue by jaws35smith** [hassio-addons/addon-grocy#63]
# Problem/Motivation

> Serial Number and Model Number and other fields would be nice to have within Grocy. 

## Expected behavior

> ability to scan bar-code for serial number and model number within the equipment tab.

## Actual behavior

> does not exist

## Steps to reproduce

> N/A

## Proposed changes

Add fields that reflect Serial Number, Model Number, Purchase amount, Purchase date, and location. If this changes were implemented Grocy could be a great product to track not only food items, but also other physical assets in a home.

**Comment by sinclairpaul** [comment]
The addon itself wraps existing software, the repo for the application itself is at https://github.com/grocy/grocy

Feature enhancements/requests would need to be logged there.
