### ISSUE TITLE
Howto set features from the grocy config.php?

### ISSUE THREAD

**Issue by Jeltel** [hassio-addons/addon-grocy#66]
There is a new feature in grocy 2.6.0 which I want to set. This is normally set in the config.php from Grocy. How do I set it with the HA addon?

https://github.com/grocy/grocy/blob/master/config-dist.php

In this case the Setting('MEAL_PLAN_FIRST_DAY_OF_WEEK', ''); But I guess this should work for all the settings from config.php.

<blockquote><img src="https://avatars0.githubusercontent.com/u/44542094?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/grocy/grocy">grocy/grocy</a></strong></div><div>ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home - grocy/grocy</div></blockquote>

**Comment by sinclairpaul** [comment]
You can't at the moment, it would need another release to support it.

**Comment by Jeltel** [comment]
That's too bad, because there are a lot of settings in that file.
I tried editing the file within a backup and then restoring that backup. But that didn't work either. 
So an option to do this for the add-on would be great. Maybe a new section in the config of the add-on which is transferred to the config.php? (Which then does work, off course).

**Comment by sinclairpaul** [comment]
The majority of them are configurable in the addon (there is a list in the readme), this particular one isn't however.
