### ISSUE TITLE
Problem update stock

### ISSUE THREAD

**Issue by yorchtf** [hassio-addons/addon-grocy#67]
# Problem/Motivation

I can nota update the stock by curl with token hassio and token grocy.

## Expected behavior

update the stock vía curl

## Steps to reproduce

I have tried the next queries:

Query:
curl -X POST \
-H "Authorization: Bearer TOKEN-KEY-HASSIO" \
-H "Content-Type: application/json" \
-H "accept: application/json" \
-u <user_grocy>:<passwd_grocy> \
-d "{\"amount\":3,\"transaction_type\":\"consume\",\"spoiled\":false}" \
"https://<endpoint_hassio>:8123/api/hassio_ingress/rAxPRtNqbnVNLiTXxV1_pSTM6YeCUTU7ZE9FDXYodIc/api/stock/products/4/consume"
Return: 401: Unauthorized

Query:
curl -X POST \
-H "Authorization: Bearer TOKEN-KEY-HASSIO" \
-H "Content-Type: application/json" \
-H "accept: application/json" \
-H "GROCY-API-KEY: TOKEN-KEY-GROCY" \
-d "{\"amount\":3,\"transaction_type\":\"consume\",\"spoiled\":false}" \
"https://<endpoint_hassio>:8123/api/hassio_ingress/rAxPRtNqbnVNLiTXxV1_pSTM6YeCUTU7ZE9FDXYodIc/api/stock/products/4/consume"
Return: 401: Unauthorized

Could you help me?

**Comment by frenck** [comment]
Ingress is for web traffic, not API traffic.
If you want to talk to the API, you need to do that directly, not via Ingress.

**Comment by yorchtf** [comment]
Replace the last URL for this one: https://<host>.duckdns.org:8123/a0d7b954_grocy/api/stock/products/4/consume ?

In the first query ir second? 

Use -u user:passwd of grocy and 
-H "Authorization: Bearer TOKEN-KEY-HASSIO" ?

 Is necessary on this case use -H "GROCY-API-KEY: TOKEN-KEY-GROCY"?

Thanks a lot!!!

**Comment by frenck** [comment]
? Not sure about the question you are asking.
You can't use any tokens from the supervisor.

If you access Grocy directly, it just works as documented by Grocy. There is no involvement from HA on that part.

**Comment by yorchtf** [comment]
I am accessing to grocy by hassio, the last URL got for this method. I want to do it the objetive on this articule http://philhawthorne.com/automating-your-shopping-list-with-home-assistant-and-grocy/

For this reason, i think to do It, a double validation, one in hassio and the second on grocy in my curl command.

Is possible accesar to grocy without hassio?

**Comment by frenck** [comment]
There is not Home Assistant involvement when accessing Grocy directly.
There is no double validation.

Assign a port in the add-on config.

**Comment by yorchtf** [comment]
Could you show me a example by curl? (To update stock) I would to execute the curl command in a remote machine and the same machine where i have installed the hassio.

**Comment by frenck** [comment]
Please consult the documentation of Grocy.
When accessing Grocy directly, there is no involvement from HA.
