### ISSUE TITLE
Enable non admin users to use the addon (Feature Request)

### ISSUE THREAD

**Issue by kayloehmann** [hassio-addons/addon-grocy#68]
# Problem/Motivation
It is currently not possible for non administrative users to gain access to the addon.

## Expected behavior
Non administrative users can navigate to the addon start page via the sidebar.

## Actual behavior
Currently not possible.

Thanks! Kay.

**Comment by frenck** [comment]
That is not an add-on limitation and thus cannot be addressed by the add-on.
