### ISSUE TITLE
Feature Request: Allow more than one manual

### ISSUE THREAD

**Issue by chadmccune** [hassio-addons/addon-grocy#69]
# Problem/Motivation
Just testing this out and I immediately ran into this issue.  The first piece of "equipment" I went to add had multiple manual files.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jackwilsdon** [comment]
This issue should be filed with [grocy](https://github.com/grocy/grocy), this repository is just the add-on for Home Assistant and isn't the repository for grocy itself.

**Comment by frenck** [comment]
Yep, @chadmccune, @jackwilsdon is correct.

Add-ons wrap applications, we don't manage the application itself. Please file that type of feature requests on the application provider itself.

Thanks! 👍
