### ISSUE TITLE
Some OK buttons not working

### ISSUE THREAD

**Issue by poudenes** [hassio-addons/addon-grocy#74]
Hi ALl,

Very interesting add-on. Tried this on 0.107.4 and have some issues with the green OK button:

![Screen Shot 2020-03-22 at 15 42 51](https://user-images.githubusercontent.com/4399532/77252446-2dd1d380-6c54-11ea-8ce3-1f6d792ee07b.png)

![Screen Shot 2020-03-22 at 15 43 17](https://user-images.githubusercontent.com/4399532/77252449-32968780-6c54-11ea-8449-a1f2937d1969.png)

![Screen Shot 2020-03-22 at 15 44 00](https://user-images.githubusercontent.com/4399532/77252452-35917800-6c54-11ea-9571-d0ce79d94e1f.png)

**Comment by jackwilsdon** [comment]
This issue is with [Grocy itself](https://github.com/grocy/grocy), this repository is just the home assistant add-on for running Grocy.

**Comment by poudenes** [comment]
Ok thanks. Will issue this to Grocy then ... Or install outside HA

**Comment by poudenes** [comment]
version in HA is 2.6.0 and they have 2.6.1
Is there a way to update it inside HA?

**Comment by jackwilsdon** [comment]
It looks like the addon hasn't been updated to 2.6.1 yet.

**Comment by frenck** [comment]
That is planned on the next maintenance cycle, it needs some adjustments to be able to run the update.

Although Grocy released it as a patch release, it did, unfortunately, contain a breaking change.

**Comment by poudenes** [comment]
good to hear !
// Keep up the good work!
