### ISSUE TITLE
Edit dialogs not closing after saving

### ISSUE THREAD

**Issue by joggs** [hassio-addons/addon-grocy#75]
# Problem/Motivation
When editing an ingredient in a recipe and save the ingredient clicking the save button you only see a spinner spinning indefinately. I get this behavior on other places as well. If you close the dialog and save the parent object, in this case the recipe, and then enter the recipe, the objects are saved as expected.

> (Why the issue was filed)

## Expected behavior
The dialog should close when you click save
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
create recipe and add ingredients and click save
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jackwilsdon** [comment]
This issue is with [Grocy itself](https://github.com/grocy/grocy), this repository is just the home assistant add-on for running Grocy.
