### ISSUE TITLE
Portuguese language support 

### ISSUE THREAD

**Issue by jfmcarreira** [hassio-addons/addon-grocy#77]
# Problem/Motivation

I would like to be able to select Portuguese language. 

This language is support by grocy application but the addon options do not allow us to select it. 
One could allow the pt_PT and pt_BR. 

## Proposed changes

Add support to select Portuguese language in the addon options.

**Comment by ddallagnol** [comment]
I also need this! 
How can we help to get this done?

**Comment by jfmcarreira** [comment]
Thanks

**Comment by ddallagnol** [comment]
We need to wait for some version update? I've uninstalled/reinstalled the addon but the "culture:" option can't still be changed to pt_BR.

**Comment by frenck** [comment]
It depends on a new release of the add-on.
