### ISSUE TITLE
chore automations

### ISSUE THREAD

**Issue by ikrowni** [hassio-addons/addon-grocy#80]
# Problem/Motivation

Create automation for chores to mark as complete

## Expected behavior

chore marked as complete upon executing automation

## Actual behavior

nothing

## Steps to reproduce

none

## Proposed changes

I've setup chores for my kids to do within the grocy addon. I want to give them a page within home assistant so that they can mark their chores as complete as they go down the list. When all chores are finished i would like to turn their internet access back on. I can handle the internet access part but i dont know how to monitor the state of a chore and mark a chore as complete

**Comment by frenck** [comment]
The add-on provides the Grocy application as a service and is not related to Home Assistant integration in any way.

So can't implement that here.
