### ISSUE TITLE
Upgrade to latest version (2.7.1)

### ISSUE THREAD

**Issue by organismen** [hassio-addons/addon-grocy#83]
First: Thanks for an awesome addon. I stumbled across Grocy by browsing the add-ons in Home assitant and I really have missed a system like this.
I'm really just curious, is there a plan du upgrade to latest release any time soon?

# Problem/Motivation

Eager to get the latest version of grocy via home assistant addon

## Expected behavior

An install of version 2.7.1 via this addon

## Actual behavior

2.6.0 installs

## Steps to reproduce

Install Grocy as a addon via home assistant supervisor

## Proposed changes

Update this addon to build from release 2.7.1

**Comment by darkcloud784** [comment]
To add to this, no update shows available to those that have already deployed it.

**Comment by sinclairpaul** [comment]
The update will happen on the next release of the addon.  There is no set schedule.
