### ISSUE TITLE
Error Updating culture

### ISSUE THREAD

**Issue by ddallagnol** [hassio-addons/addon-grocy#87]
I've already uninstalled/re-downloaded the addon, but I still can't change the culture option to pt_BR...

Error message:
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'culture': 'pt_BR', 'currency': 'USD', ...

**Comment by jackwilsdon** [comment]
A new release containing the changes from #77 hasn't been published yet. https://github.com/hassio-addons/addon-grocy/issues/77#issuecomment-630945311

**Comment by frenck** [comment]
Grocy 0.8.0 has just been released.
