### ISSUE TITLE
Error when trying to edit stock entry with Grocy addon version 0.8.0

### ISSUE THREAD

**Issue by Anwen747** [hassio-addons/addon-grocy#88]
# Problem/Motivation

> (Why the issue was filed)
Thanks for this great addon - I am finding it really useful during this pandemic we are living through right now.  I've just updated the addon to 0.8.0, and I cannot edit stock entries anymore.  Using the edit button on a stock entry opens the edit window, but when I try to save changes, they will not save and an error is generated in the log.
## Expected behavior

> (What you expected to happen)
Editing a stock entry to change the expiration date or location should work.  It worked in the previous version.
## Actual behavior

> (What actually happened)
When I click _Okay_ after doing the edit, I just get a spinning circle until I click _Cancel_.   No change is made to the entry.  I see this error in the Grocy addon log:

`2020/05/31 14:19:05 [error] 923#923: *66 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: nextInputSelector in /data/grocy/viewcache/23b0f6eb24ccc18da3d06dcd04960ed02aab5979.php on line 10PHP message: PHP Notice:  Undefined variable: hintId in /data/grocy/viewcache/23b0f6eb24ccc18da3d06dcd04960ed02aab5979.php on line 11" while reading response header from upstream, client: 192.168.0.18, server: a0d7b954-grocy, request: "GET /stockentry/793?embedded HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.0.151:9654", referrer: "http://192.168.0.151:9654/stockentries?product=62"`

I am not sure if this is an addon issue or a Grocy issue.  In searching the Grocy GitHub, I do not see others reporting this issue.  My HA install is as follows:

 System: Ubuntu 18.04.4 LTS  (amd64 / intel-nuc)
 Home Assistant Core: 0.110.3
 Home Assistant Supervisor: 225

The error occurs both when I use the addon via Ingress (from the HA sidebar) and when I access the addon from a port set for the web interface.

Thank you very much.
## Steps to reproduce

> (How can someone else make/see it happen)
Edit a stock entry and try to save the changes.
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Looks like I can duplicate, although I do see the data (well changing the dates) seems to get updated.

Do you see a message like `Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '/api/hassio_ingress/eOAPmOhSjvoMXGYzdlovtMcS7n53HZTGuKbEDfxgV7I/' in a call to 'postMessage'` in the Browser Devtools?

**Comment by Anwen747** [comment]
I'm using Chrome on a PC.  Using the Chrome dev tools, when I open the edit window when Grocy is open from the sidebar, I get this in the console:

```
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:8123/api/hassio_ingress/YFvVExsYqLz6UjfMwKVMKZvgdmULifu4R5BmlWlL-FM/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:8123/api/hassio_ingress/YFvVExsYqLz6UjfMwKVMKZvgdmULifu4R5BmlWlL-FM/node_modules/toastr/build/toastr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:8123/api/hassio_ingress/YFvVExsYqLz6UjfMwKVMKZvgdmULifu4R5BmlWlL-FM/node_modules/sprintf-js/dist/sprintf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:8123/api/hassio_ingress/YFvVExsYqLz6UjfMwKVMKZvgdmULifu4R5BmlWlL-FM/node_modules/bootstrap-select/dist/js/bootstrap-select.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:8123/api/hassio_ingress/YFvVExsYqLz6UjfMwKVMKZvgdmULifu4R5BmlWlL-FM/node_modules/summernote/dist/summernote-bs4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
and when I change the date and click okay I get

```
stockentryform.js?v=2.7.1:18 
Uncaught TypeError: Cannot read property 'GetValue' of undefined
    at HTMLButtonElement.<anonymous> (VM789 stockentryform.js:18)
    at HTMLButtonElement.dispatch (jquery.min.js?v=2.7.1:2)
    at HTMLButtonElement.v.handle (jquery.min.js?v=2.7.1:2)
```
If I open a tab using the web interface, I get this when I open the edit window:
```
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/toastr/build/toastr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/sprintf-js/dist/sprintf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/summernote/dist/summernote-bs4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/bootstrap-select/dist/js/bootstrap-select.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
and when I click okay:
```
Uncaught TypeError: Cannot read property 'GetValue' of undefined
    at HTMLButtonElement.<anonymous> (VM156 stockentryform.js:18)
    at HTMLButtonElement.dispatch (jquery.min.js?v=2.7.1:2)
    at HTMLButtonElement.v.handle (jquery.min.js?v=2.7.1:2)
(anonymous) @ VM293 stockentryform.js:18
dispatch @ VM257 jquery.min.js:2
v.handle @ VM257 jquery.min.js:2
```
I don't see the message you gave, unless I'm doing the wrong thing or looking in the wrong place...

**Comment by Anwen747** [comment]
And I just discovered Purchasing isn't working either, just sits there with a spinning circle after I click _Okay_.  Error string is:

```DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/toastr/build/toastr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/summernote/dist/summernote-bs4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/sprintf-js/dist/sprintf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/bootstrap-select/dist/js/bootstrap-select.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
purchase.js?v=2.7.1:155 Uncaught TypeError: Cannot read property 'SetId' of undefined
    at purchase.js?v=2.7.1:155
    at XMLHttpRequest.xhr.onreadystatechange (grocy.js?v=2.7.1:17)
(anonymous) @ purchase.js?v=2.7.1:155
xhr.onreadystatechange @ grocy.js?v=2.7.1:17
XMLHttpRequest.send (async)
Grocy.Api.Get @ grocy.js?v=2.7.1:36
(anonymous) @ purchase.js?v=2.7.1:143
dispatch @ jquery.min.js?v=2.7.1:2
v.handle @ jquery.min.js?v=2.7.1:2
trigger @ jquery.min.js?v=2.7.1:2
(anonymous) @ jquery.min.js?v=2.7.1:2
each @ jquery.min.js?v=2.7.1:2
each @ jquery.min.js?v=2.7.1:2
trigger @ jquery.min.js?v=2.7.1:2
select @ bootstrap-combobox.js?v=2.7.1:123
click @ bootstrap-combobox.js?v=2.7.1:436
i @ jquery.min.js?v=2.7.1:2
dispatch @ jquery.min.js?v=2.7.1:2
v.handle @ jquery.min.js?v=2.7.1:2
bootstrap.bundle.min.js?v=2.7.1:6 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at Object.onLoad (bootstrap.bundle.min.js?v=2.7.1:6)
    at bootstrap.bundle.min.js?v=2.7.1:6
    at Array.forEach (<anonymous>)
    at new Dt (bootstrap.bundle.min.js?v=2.7.1:6)
    at c.e.show (bootstrap.bundle.min.js?v=2.7.1:6)
    at c.e.toggle (bootstrap.bundle.min.js?v=2.7.1:6)
    at HTMLSpanElement.<anonymous> (bootstrap.bundle.min.js?v=2.7.1:6)
    at Function.each (jquery.min.js?v=2.7.1:2)
    at k.fn.init.each (jquery.min.js?v=2.7.1:2)
    at k.fn.init.c._jQueryInterface [as dropdown] (bootstrap.bundle.min.js?v=2.7.1:6)
onLoad @ bootstrap.bundle.min.js?v=2.7.1:6
(anonymous) @ bootstrap.bundle.min.js?v=2.7.1:6
Dt @ bootstrap.bundle.min.js?v=2.7.1:6
e.show @ bootstrap.bundle.min.js?v=2.7.1:6
e.toggle @ bootstrap.bundle.min.js?v=2.7.1:6
(anonymous) @ bootstrap.bundle.min.js?v=2.7.1:6
each @ jquery.min.js?v=2.7.1:2
each @ jquery.min.js?v=2.7.1:2
c._jQueryInterface @ bootstrap.bundle.min.js?v=2.7.1:6
(anonymous) @ bootstrap.bundle.min.js?v=2.7.1:6
dispatch @ jquery.min.js?v=2.7.1:2
v.handle @ jquery.min.js?v=2.7.1:2
purchase.js?v=2.7.1:33 Uncaught TypeError: Cannot read property 'GetValue' of undefined
    at purchase.js?v=2.7.1:33
    at XMLHttpRequest.xhr.onreadystatechange (grocy.js?v=2.7.1:17)
(anonymous) @ purchase.js?v=2.7.1:33
xhr.onreadystatechange @ grocy.js?v=2.7.1:17
XMLHttpRequest.send (async)
Grocy.Api.Get @ grocy.js?v=2.7.1:36
(anonymous) @ purchase.js?v=2.7.1:8
dispatch @ jquery.min.js?v=2.7.1:2
v.handle @ jquery.min.js?v=2.7.1:2
```
Consuming works, so some of it is working...

**Comment by sinclairpaul** [comment]
Purchasing works ok for me, you may want to clear the Javascripts from cache and retry in case there was a versioning issue (or clear the browser cache completely).

**Comment by sinclairpaul** [comment]
I also want to add, if I expose the addon I do not see the issues, so would suggest running Incognito while the addon is exposed to confirm.

**Comment by Anwen747** [comment]
A soon as I open Grocy exposed in an incognito window I get the string of errors:

```
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/toastr/build/toastr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/sprintf-js/dist/sprintf.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/summernote/dist/summernote-bs4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.0.151:9654/node_modules/bootstrap-select/dist/js/bootstrap-select.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
and I see the same errors as posted earlier when trying to purchase or edit stock entries. I have done Empty Cache & Hard Reload several times; it doesn't change anything.  I'm not sure what to do next.  If I uninstall and reinstall the addon, will I lose my database?

**Comment by sinclairpaul** [comment]
The sourcemap errors aren't really relevant.

Unfortunately yes an uninstall would remove the DB, but it probably wouldn't help anyway.

At this point all I can suggest is to roll back to a snap if you have one, although I'm not sure how we will investigate the errors.

**Comment by Anwen747** [comment]
I had installed Grocy Desktop on my PC a couple of weeks back to see what it was like.  (I'm not actively using it.)  When I look at that, I see that there are new options, for example, Store, in the Purchase window.  I don't see that in my Grocy addon, although supposedly they are running the same version (2.7.1) of Grocy.  That seems odd!

**Comment by sinclairpaul** [comment]
Like 
![image](https://user-images.githubusercontent.com/24625998/83363338-c9737480-a366-11ea-9c03-36a3be9b0cf7.png)

Can you please post the addon startup log, in particular the piece

```
-----------------------------------------------------------
 Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.4 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.110.0.dev20200504
 Home Assistant Supervisor: 224
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

**Comment by Anwen747** [comment]
I restarted the addon, here's the log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-grocy: applying... 
[fix-attrs.d] 01-grocy: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.4 LTS  (amd64 / intel-nuc)
 Home Assistant Core: 0.110.3
 Home Assistant Supervisor: 225
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[cont-init.d] grocy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:51:03] INFO: Starting PHP-FPM...
[17:51:04] INFO: Starting NGinx....
```

I see this:

![grocypurchase](https://user-images.githubusercontent.com/51857150/83363452-8bc31b80-a367-11ea-87fa-6a4390bc7089.JPG)

**Comment by sinclairpaul** [comment]
Not really sure what to add here, the addon is updated to the latest version, unless its a caching issue somewhere you should be seeing the UI correctly.

**Comment by Anwen747** [comment]
Thank you so much for trying to work through this with me, it's really appreciated!

I just tried using Vivaldi and Microsoft Edge, neither of which I have used since I've installed the Grocy addon a couple of months ago, and I don't see the right UI there either.  I'm well and truly stumped right now.

**Comment by Anwen747** [comment]
And I'm back in business.  I put all the options in the addon configuration back to default, set SSL to false because I'm not using that, and restarted the addon.  And now I see the correct UI, and purchasing works correctly.  I still get the spinning wheel if I use the addon with Ingress when I edit stock entries, but it does change the data now.  And if I use it exposed, I don't get the spinning wheel and it works properly.  I did have the battery tracking set to false previously.

Later I will see what happens if I change configuration options, but I have other things that need to be done tonight.  Thank you so much for all your help - I really appreciate the time you spent helping me with this.

**Comment by Anwen747** [comment]
Just to follow up...I have now changed my addon configuration, setting various parameters like batteries, equipment, multiple shopping lists, to false, and I am having no issues using the addon.  I continue to have a spinning wheel issue when using Ingress to edit stock entries, but it does update the data, and that's what counts.  I do not have that issue if I use it exposed.

Thanks again for all the help.  I think this issue can be closed (do I do that, or do you?)
