### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by OmgImAlexis** [hassio-addons/addon-grocy#9]
# Problem/Motivation

I was trying to upload a manual in the equipment section. My PDF is `3.1M`.

## Expected behavior

File to upload.

## Actual behavior

Error showed.
```
"\r\n\r\n\r\n
413 Request Entity Too Large
\r\n
nginx/1.14.2
\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
```

## Steps to reproduce

Upload a `3.1M` file.

## Proposed changes

Increase the nginx limit to 500MB.

Based on [this](https://serverfault.com/a/814774/278751) SO answer it looks like this is the line that's needed.
```
client_max_body_size 500M;
```

**Comment by frenck** [comment]
Fixed in current dev, thank you for reporting! ❤️
