### ISSUE TITLE
403 Forbidden nginx (ingress only)

### ISSUE THREAD

**Issue by jkmf** [hassio-addons/addon-grocy#91]
# Problem/Motivation

On my fresh install of hass.io I can't use grocy add-on using ingress. I get "403 Forbidden" message.

## Expected behavior

> (What you expected to happen)

## Actual behavior

`2020/06/18 12:50:24 [error] 802#802: *1 access forbidden by rule, client: 172.30.32.1, server: a0d7b954-grocy, request: "GET / HTTP/1.1", host: "myhostname:8123", referrer: "https://myhostname:8123/a0d7b954_grocy"
[18/Jun/2020:12:50:24 +0200] 403 192.168.xx.xx, 172.30.32.1(172.30.32.1) GET / HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36)`

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

To fix the issue I need to put:
`allow   172.30.32.1;`
in file: `/etc/nginx/servers/ingress.conf`
and restart nginx:
`service nginx restart`

**Comment by frenck** [comment]
Ingress should not originate from 172.30.32.1, so that makes no sense?

**Comment by jkmf** [comment]
I did some research and found another solution.
The problem was one of the iptables MASQUERADE rule:

```
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            
MASQUERADE  all  --  172.30.32.0/23       anywhere            
MASQUERADE  all  --  anywhere             anywhere            
MASQUERADE  tcp  --  172.30.33.0          172.30.33.0          tcp dpt:1883
```
after removing:

`MASQUERADE  all  --  anywhere             anywhere     `

grocy works like a charm.
