### ISSUE TITLE
Czech language

### ISSUE THREAD

**Issue by PavelkaDavid** [hassio-addons/addon-grocy#92]
# Problem/Motivation

In configuration I cannot set up Czech language. Code "cs" ([https://github.com/grocy/grocy/tree/master/localization](https://github.com/grocy/grocy/tree/master/localization))

## Expected behavior

Be able to set it as in official configuration.

## Actual behavior

When setting "cs" in configuration, I get following error:
`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'culture': 'cs', 'currency': 'CZK', 'entry_page': 'stock', 'features': {'batteries': True, 'calendar': True, 'chores': True, 'equipment': True, 'recipes': True, 'shoppinglist': True, 'stock': True, 'tasks': True}, 'tweaks': {'chores_assignment': True, 'multiple_shopping_lists': True, 'stock_best_before_date_tracking': True, 'stock_location_tracking': True, 'stock_price_tracking': True, 'stock_product_freezing': True, 'stock_product_opened_tracking': True}, 'ssl': True, 'certfile': 'fullchain...`

## Steps to reproduce

Set configuration to this:
`culture: cs
currency: CZK
entry_page: stock
features:
  batteries: true
  calendar: true
  chores: true
  equipment: true
  recipes: true
  shoppinglist: true
  stock: true
  tasks: true
tweaks:
  chores_assignment: true
  multiple_shopping_lists: true
  stock_best_before_date_tracking: true
  stock_location_tracking: true
  stock_price_tracking: true
  stock_product_freezing: true
  stock_product_opened_tracking: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
`

<blockquote><img src="https://avatars0.githubusercontent.com/u/44542094?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/grocy/grocy">grocy/grocy</a></strong></div><div>ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home - grocy/grocy</div></blockquote>

**Comment by frenck** [comment]
Fixed in the latest dev version, will be part of the next add-on release.
Thanks for reporting this 👍
