### ISSUE TITLE
Grocy via Home Assistant Ingress only works for users that are Admins in Home Assistant

### ISSUE THREAD

**Issue by int-rnd** [hassio-addons/addon-grocy#94]
# Problem/Motivation
Grocy works great for Admins in HA but not for regular users. Not sure if this is a Grocy issue or an HA Ingress issue.

## Expected behavior
Grocy should work for all users OR be able to assign permissions to users in HA.

## Actual behavior
401 Unauthorized

## Steps to reproduce
Install the Grocy Add-on in supervisor.
See that it works when you are logged into HA as an admin user.
Create/use a non admin user in HA.
Log out of HA and log back into HA as a regular user.
Attempt to get to Grocy... it won't even show up.
(bonus) Say you copied the assigned Ingress URL, attempt to use that while logged into HA as a regular user - should get 401 unauthorized.

## Proposed changes

Allow non-admin users to use Grocy via Ingress.

##Version Info
Grocy version: 0.9.0 (version showing in supervisor)

arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.8.3
supervisor | 229
version | 0.113.1
virtualenv | false

**Comment by frenck** [comment]
This is not something the add-on can fix. Add-on interfaces are only available to Admin users.
