### ISSUE TITLE
Significant slowdown over time

### ISSUE THREAD

**Issue by Vader266** [hassio-addons/addon-grocy#95]
# Problem/Motivation
Grocy, while initially very nippy, has ground to almost a halt, rendering it unusable.

## Expected behavior
Meal Plan and Recipe access should be as quick as the rest of Grocy, or at least in the same ballpark.

## Actual behavior
When accessing the Meal Plan or Recipes, Grocy hangs for up 30 seconds to load the page. This hang is duplicated if I open a new recipe.

## Steps to reproduce
I'm not sure how to reproduce this, but it has developed over time. Hopping around the other tabs (Stock overview, Chore etc) is initially slow as well but speeds up on later access.

Logs do not display any odd behaviour, just the usual GET requests.

## Proposed changes
Could this be an issue of increasing archive access time for the records and/or the images we have on-file? The meal plan in particular is heavily used so it could be an inefficient storage structure. Has anyone else experienced similar issues?

**Comment by Vader266** [comment]
Second post as tax on my own stupidity:
I'm running Grocy on Hassio in a VM on windows. It has dedicated access to 2 cores on an i5 and 2 GB of RAM. Find attached the latest log window after having a play to check the issue.

[log.txt](https://github.com/hassio-addons/addon-grocy/files/5023547/log.txt)

**Comment by frenck** [comment]
Those logs look fine and are merely access logs from the nginx webserver.
As for the slowness, this might be caused by database size/usage?

Whatever the case, this add-on wraps existing software, in this case Grocy. Please report your issue with Grocy itself. Thanks 👍
