### ISSUE TITLE
JSON serialize error after update Home Assistant

### ISSUE THREAD

**Issue by hukoeth** [hassio-addons/addon-grocy#97]
# Problem/Motivation
Since updating to Home Assistant 0.114.2 I get errors when trying to use the grocy addon.

## Expected behavior
Addon working

## Actual behavior
When activated, the frontend won't load (hanging on the load screen) with the error

`Uncaught (in promise) 
{
  "code": "unknown_error",
  "message": "Invalid JSON in response"
}`

Home Assistant log shows error:

`2020-08-20 11:15:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2396777104] Unable to serialize to JSON. Bad data found at $.result[152](state: sensor.grocy_shopping_list).attributes.items[0].product=<pygrocy.grocy_api_client.ProductData object at 0x8fc7da70>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[1].product=<pygrocy.grocy_api_client.ProductData object at 0x8f0a98b0>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[2].product=<pygrocy.grocy_api_client.ProductData object at 0x8f121250>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[3].product=<pygrocy.grocy_api_client.ProductData object at 0x8ed80e70>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[4].product=<pygrocy.grocy_api_client.ProductData object at 0x8f115630>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[5].product=<pygrocy.grocy_api_client.ProductData object at 0x8ef394d0>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[6].product=<pygrocy.grocy_api_client.ProductData object at 0x8ef585d0>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[7].product=<pygrocy.grocy_api_client.ProductData object at 0x8e729710>(<class 'pygrocy.grocy_api_client.ProductData'>, $.result[152](state: sensor.grocy_shopping_list).attributes.items[8].product=<pygrocy.grocy_api_client.ProductData object at 0x8e729750>(<class 'pygrocy.grocy_api_client.ProductData'>`

## Steps to reproduce
Install latest version of Home Assistant Core, Install latest version of grocy add-on, Configure add-on, Restart Home Assistant

**Comment by ludeeus** [comment]
This is not an issue with the add-on, those logs are from the custom_component, you should report it there.
