### ISSUE TITLE
error 404 when adding product from purchase menu

### ISSUE THREAD

**Issue by bbass101** [hassio-addons/addon-grocy#99]
# Problem/Motivation
If a product does not exist when trying to purchase, it will let me add it. When saving the addition, an error404 screen is returned.
## Expected behavior
not error 404
## Actual behavior
Error 404 details:
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
## Steps to reproduce
On the purchase tab, attempt to add a product that does not exist. Hit create product (shortcut "a"), give it a name, and attempt to save it.

**Comment by cslux** [comment]
I came across this issue too, and I think I found the reason. I use my apache running on the server as reverse proxy for HA and forward everything to the Pi. While looking at the URLs in to apache logfiles more closely and comparing them with the Wireshark captures when connected to the grocy addon locally. I found out that the query string "...returnto=..." is wrong.

from the apache logfile:
`product/new?prefillname=Limette&returnto=/https://example.comshoppinglistitem/new`

If I remove "https://example.com" everything works fine. I don't think this is a problem with my apache configuration.

localhost:

`/product/new?prefillname=Melone&returnto=/shoppinglistitem/new`

**Comment by sinclairpaul** [comment]
We looked at this previously in #36 #55 #58 and #78 

There seems to be some changes upstream related to using relative pathing, but need to wait on a release.

**Comment by Nick-Case** [comment]
Also having this issue when adding ingredients from a recipe page, and also adding ingredients to a recipe.

Rather frustrating first hour of Grocy, but I'll stick with it.

Is there a workaround?

**Comment by sinclairpaul** [comment]
> Is there a workaround?

You can configure the addon with a separate network port, and the errors should not occur.

**Comment by Nick-Case** [comment]
> > Is there a workaround?
> 
> You can configure the addon with a separate network port, and the errors should not occur.

This worked a treat, thanks. Might be worth popping this in the docs as a known issue & workaround?
